import { readFile, stat, access } from 'node:fs/promises';
import assert from 'node:assert/strict';

const domain = 'https://howtofishwalkthrough.com';
const routes = ['/', '/beginner-guide', '/creatures', '/bosses', '/locations', '/locations/lighthouse', '/guides/reel-of-fortune', '/lures', '/bosses/spider-crab', '/achievements', '/about', '/contact', '/privacy', '/terms'];
const prerenderSource = await readFile('scripts/prerender.ts', 'utf8');
assert.match(prerenderSource, /renderToString\(React\.createElement\(App/, 'static pages must render the shared React App tree with the hydration-compatible API');
const clientSource = await readFile('src/client.tsx', 'utf8');
assert.match(clientSource, /hydrateRoot\(/, 'client entry must hydrate the server-rendered App');
const appSource = await readFile('src/main.tsx', 'utf8');
assert.match(appSource, /useState<string\[\]>\(\[\]\);const \[hydrated,setHydrated\]=useState\(false\)/, 'creature SSR and first client render must start with an empty checklist');
assert.match(appSource, /useEffect\(\(\)=>\{try\{const raw=JSON\.parse\(localStorage\.getItem\('htf-caught'\)/, 'creature checklist must restore validated local storage after mount');
assert.match(appSource, /if\(hydrated\)localStorage\.setItem\('htf-caught'/, 'creature checklist must not persist before restore completes');
assert.match(appSource, /set\('og:type',known\?'article':'website',true\)/, 'known client pages must use article Open Graph type');
assert.match(appSource, /index,follow,max-image-preview:large/, 'indexable pages must allow large image previews');
const stylesSource = await readFile('src/styles.css', 'utf8');
assert.match(stylesSource, /\.guide-visual\{margin:30px 0;overflow-x:auto/, 'mobile guide visuals must support horizontal scrolling');
assert.match(stylesSource, /Swipe or scroll the diagram horizontally/, 'mobile guide visuals must explain the scroll affordance');
for (const route of routes) {
  const file = route === '/' ? 'dist/index.html' : `dist${route}/index.html`;
  await stat(file);
  const html = await readFile(file, 'utf8');
  assert.match(html, new RegExp(`<link rel="canonical" href="${domain}${route === '/' ? '/' : route}">`));
  assert.match(html, /<meta property="og:title"/);
  assert.match(html, /<meta name="twitter:card" content="summary_large_image">/);
  assert.match(html, /application\/ld\+json/);
  assert.match(html, /<meta name="robots" content="index,follow,max-image-preview:large">/);
  assert.doesNotMatch(html, /<div id="root"><\/div>/);
}
const creatures = await readFile('dist/creatures/index.html', 'utf8');
assert.match(creatures, /All 49 How to Fish/);
assert.match(creatures, /Mutated Bowhead Whale/);
const home = await readFile('dist/index.html', 'utf8');
assert.match(home, /aria-label="Original How to Fish gameplay field images"/, 'homepage must expose the original-material carousel');
const homeImages = [...home.matchAll(/src="(\/images\/home\/[^"]+\.webp)"/g)].map(match => match[1]);
assert.equal(homeImages.length, 4, 'homepage carousel must include all four processed gameplay frames');
for (const src of homeImages) await access(`public${src}`);
assert.equal((await readFile('dist/ads.txt', 'utf8')).trim(), 'google.com, pub-5329936944958399, DIRECT, f08c47fec0942fa0', 'ads.txt must exactly match the authorized seller record');
const privacy = await readFile('dist/privacy/index.html', 'utf8');
for (const phrase of ['Google AdSense', 'local storage', 'Google-certified consent management platform', 'My Ad Center']) assert.match(privacy, new RegExp(phrase));
const about = await readFile('dist/about/index.html', 'utf8');
for (const path of ['/about','/contact','/privacy','/terms']) assert.match(about, new RegExp(`href="${path}"`));
const spider = await readFile('dist/bosses/spider-crab/index.html', 'utf8');
assert.match(spider, /Empty Beer Can/);
const textFrom = html => html.replace(/<script[\s\S]*?<\/script>/g, ' ').replace(/<style[\s\S]*?<\/style>/g, ' ').replace(/<[^>]+>/g, ' ').replace(/&[a-z#0-9]+;/gi, ' ').replace(/\s+/g, ' ').trim();
const contentGate = async (route, requirements) => {
  const html = await readFile(`dist${route}/index.html`, 'utf8');
  assert.ok(textFrom(html).split(' ').length >= 700, `${route} must have at least 700 visible words`);
  assert.ok((html.match(/<img /g) || []).length >= requirements.images, `${route} must include original explanatory visuals`);
  for (const phrase of requirements.phrases) assert.match(html, new RegExp(phrase), `${route} missing required player-help content: ${phrase}`);
  assert.match(html, /"@type":"Article"/, `${route} must expose Article structured data`);
  assert.match(html, /"@type":"BreadcrumbList"/, `${route} must expose BreadcrumbList structured data`);
  assert.equal((html.match(/id="ld-json"/g) || []).length, 1, `${route} must emit exactly one server JSON-LD node for client replacement`);
  if (requirements.sources) {
    assert.match(html, /SOURCES \/ VERIFY/, `${route} must expose source links`);
    assert.match(html, /pcgamer\.com\/games\/sim\/how-to-fish-spider-crab/, `${route} must cite PC Gamer`);
    assert.match(html, /gamesradar\.com\/games\/co-op\/how-to-fish-spider-crab/, `${route} must cite GamesRadar+`);
    assert.match(html, /steamcommunity\.com\/app\/4001890\/announcements/, `${route} must cite the official patch feed`);
    assert.match(html, /douyin\.com\/search\/%E6%B8%94%E5%8A%9B%E5%85%A8%E5%BC%80/, `${route} must cite the direct-frame Douyin review`);
    assert.match(html, /xiaohongshu\.com\/explore\/6a8aaf56000000001700b59b/, `${route} must cite the direct-frame Xiaohongshu review`);
    assert.match(html, /Evidence boundary: the Douyin and Xiaohongshu clips were directly frame-reviewed/, `${route} must state the visual-evidence boundary`);
  }
  for (const src of [...html.matchAll(/<img[^>]+src="([^"]+)"/g)].map(match => match[1])) await access(`public${src}`);
  assert.match(html, /class="article guide-article"/, `${route} must be server-rendered from the shared guide tree`);
};
await contentGate('/beginner-guide', { images: 9, sources: false, phrases: ['First 20 minutes', 'Bait and hotspots', 'Make more money', 'Prepare for Spider Crab', 'The complete five-location story route', 'Late-game firepower', 'If the route stalls', 'Empty Beer Can', 'Spider Crab Meat', 'VOLCANO'] });
const beginner = await readFile('dist/beginner-guide/index.html', 'utf8');
assert.doesNotMatch(beginner, /Claim sources|SOURCES \/ VERIFY/, '/beginner-guide must not render the removed claim-sources section');
await contentGate('/bosses/spider-crab', { images: 2, sources: true, phrases: ['Summon Spider Crab correctly', 'charge → stun → punish', 'Common mistakes and quick recoveries', 'Empty Beer Can', 'boat keys'] });
const lighthouse = await readFile('dist/locations/lighthouse/index.html', 'utf8');
assert.ok(textFrom(lighthouse).split(' ').length >= 900, '/locations/lighthouse must be a deep guide');
assert.ok((lighthouse.match(/<img /g) || []).length >= 10, '/locations/lighthouse must include the extracted gameplay sequence');
for (const phrase of ['Build the Clam-to-cash loop', 'Empty Beer Can', 'charge-and-punish', 'Boat Keys', 'FOLLOW THE GREEN FOREST MARKER']) assert.match(lighthouse, new RegExp(phrase));
for (const src of [...lighthouse.matchAll(/<img[^>]+src="([^"]+)"/g)].map(match => match[1])) await access(`public${src}`);
const locationsGuide = await readFile('dist/locations/index.html', 'utf8');
assert.ok(textFrom(locationsGuide).split(' ').length >= 1000, '/locations must be a deep five-location route');
for (const phrase of ['FIVE-LOCATION STORY ROUTE','Giant Piranha Skeleton','Pufferfish Fin','Albatross Head','Mutated Bowhead Whale','Developer Island is optional','Patch 1.0.10']) assert.match(locationsGuide, new RegExp(phrase));
assert.match(locationsGuide, /five-location-route-hero\.png/);
await access('public/images/guides/locations/five-location-route-hero.png');
const reel = await readFile('dist/guides/reel-of-fortune/index.html', 'utf8');
assert.ok(textFrom(reel).split(' ').length >= 900, '/guides/reel-of-fortune must be a deep guide');
for (const phrase of ['Drip creature','cosmetic skin','Z or C','GOLD GOLD GOLD','no stat improvement','Claim sources and limits','Patch 1.0.10']) assert.match(reel, new RegExp(phrase, 'i'));
assert.match(reel, /reel-machine-hero\.png/);
assert.doesNotMatch(reel, /there is one machine (?:on|per) (?:each|every) island|skins? (?:are|is) shared (?:between|with) players|pity (?:counter|system) guarantees/i);
await access('public/images/guides/reel-of-fortune/reel-machine-hero.png');
console.log(`verified ${routes.length} crawlable static routes`);
