/**
 * Static route generator. It imports the single typed content source so search
 * engines receive route-specific, crawlable HTML without relying on client JS.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { achievements, bosses, creatures, locations, pageMeta } from '../src/data';

const domain = 'https://howtofishwalkthrough.com';
const routes = Object.keys(pageMeta);
const escape = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const header = `<header><a class="brand" href="/"><span class="brand-mark">◉</span><span>HOW TO FISH<em> WALKTHROUGH</em></span></a><nav id="primary-navigation"><a href="/beginner-guide">Beginner Guide</a><a href="/creatures">Creature List</a><a href="/bosses">Boss Guides</a><a href="/locations">Locations</a><a href="/lures">Lures</a></nav></header>`;
const footer = `<footer><div class="footer-brand">HOW TO FISH <span>WALKTHROUGH</span></div><p>Independent player-made guide for the Dazed Games fishing simulator. Not affiliated with Dazed Games.</p><p class="source-links">Sources: <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3789629297">Steam Community 49-creature field guide</a> · <a href="https://steamcommunity.com/sharedfiles/filedetails/?id=3788027308">Steam Community 28-achievement guide</a> · <a href="https://www.destructoid.com/complete-how-to-fish-game-walkthrough-100-completion/">Destructoid walkthrough</a></p></footer>`;
const layout = (content: string) => `${header}<main>${content}</main>${footer}`;
const cards = (items: string[]) => items.map((item, index) => `<li><span>${String(index + 1).padStart(2, '0')}</span>${escape(item)}</li>`).join('');

function contentFor(path: string) {
  if (path === '/') return `<section class="hero"><div class="hero-copy"><p class="eyebrow">THE UNOFFICIAL FIELD GUIDE</p><h1>How to Fish<br><i>Walkthrough &amp; Guides</i></h1><p class="lede">How to Fish is a 2026 co-op fishing simulator by Dazed Games. Chart every creature, boss, lure, and main location with a route built for new crews.</p><a class="button primary" href="/beginner-guide">Start at the Lighthouse →</a></div></section><section class="status-strip"><div><strong>49</strong><span>CREATURES LOGGED</span></div><div><strong>11</strong><span>BOSS &amp; SPECIALS</span></div><div><strong>5</strong><span>MAIN LOCATIONS</span></div><div><strong>28</strong><span>ACHIEVEMENTS</span></div></section><section class="link-matrix"><a href="/lures">Lures &amp; Bait →</a><a href="/achievements">28 Achievements →</a><a href="/bosses/spider-crab">Spider Crab Guide →</a></section>`;
  if (path === '/beginner-guide') return `<article class="article"><p class="eyebrow">FIRST SESSION ROUTE</p><h1>How to Fish Game<br><i>Beginner Guide</i></h1><p class="standfirst">Start at Lighthouse, buy only what advances your next objective, and treat lure upgrades as collection milestones. This is a Game walkthrough, not a real-world fishing tutorial.</p><div class="trust"><b>Checked Aug 27, 2026</b><span>Source-backed against the linked Steam Community and Destructoid guides.</span></div><h2>Start with the Lighthouse loop</h2><p>Lighthouse is the starting location. Learn casting, sell catches, and advance the current objective before spending on optional gear.</p><h2>Take special encounters deliberately</h2><p>Spider Crab uses an Empty Beer Can at Lighthouse. Boss and special creatures use explicit summons, while regular creature pools advance with lure progression.</p><a class="button primary" href="/bosses/spider-crab">Next: Spider Crab guide →</a></article>`;
  if (path === '/creatures') return `<section class="hub"><p class="eyebrow">COLLECTION TOOL</p><h1>All 49 How to Fish<br><i>Game Creatures</i></h1><p class="standfirst">38 regular creatures and 11 boss or special creatures. The interactive version lets players search, filter, and save a local checklist.</p><ol class="achievement-list">${cards(creatures.map(c => `${c.name} — ${c.kind}`))}</ol></section>`;
  if (path === '/bosses') return `<section class="hub"><p class="eyebrow">SPECIAL ENCOUNTERS</p><h1>All How to Fish Game<br><i>Bosses</i></h1><p class="standfirst">Every verified special summon and route cue for the 11 boss or special creatures.</p><div class="boss-grid">${bosses.map((boss, index) => `<article class="boss"><span>${String(index + 1).padStart(2, '0')}</span><h2>${escape(boss.name)}</h2><p>${escape(boss.note)}</p><p><b>Summon:</b> ${escape(boss.summon)}</p><p><b>Route:</b> ${escape(boss.route)}</p>${boss.name === 'Spider Crab' ? '<a href="/bosses/spider-crab">Read Spider Crab guide →</a>' : ''}</article>`).join('')}</div></section>`;
  if (path === '/locations') return `<section class="hub"><p class="eyebrow">MAIN ROUTE CHART</p><h1>How to Fish Game<br><i>Locations &amp; Islands</i></h1><p class="standfirst">Five main locations: Lighthouse plus Forest, Desert, Rocks, and Volcano. Developer Island is a secret testing area, not a normal main-route location.</p><div class="location-cards">${locations.map(location => `<article><h2>${escape(location.name)}</h2><b>${escape(location.type)}</b><p>${escape(location.detail)}</p></article>`).join('')}</div></section>`;
  if (path === '/lures') return `<section class="hub"><p class="eyebrow">COLLECTION SYSTEM</p><h1>How to Fish Game<br><i>Lures &amp; Bait</i></h1><p class="standfirst">Regular creature collection advances through lure progression rather than a fixed island-only table. Exact ordinary-creature lure assignments are omitted until independently verified.</p><div class="lure-layout"><div><article class="lure"><h2>Progression lure pools</h2><p>Beginner, Standard, Professional, and Scientific lures are the four regular progression tiers.</p></article></div><aside><p class="eyebrow">VERIFIED SPECIAL SUMMONS</p>${bosses.map(boss => `<p><b>${escape(boss.summon)}</b><span>${escape(boss.name)}</span></p>`).join('')}</aside></div></section>`;
  if (path === '/bosses/spider-crab') return `<article class="article"><p class="eyebrow">LIGHTHOUSE ENCOUNTER</p><h1>How to Beat Spider Crab<br><i>in How to Fish Game</i></h1><p class="standfirst">Spider Crab is a special Lighthouse encounter. It is not an ordinary fish entry: summon it with an Empty Beer Can.</p><div class="trust"><b>Checked Aug 27, 2026</b><span>Source-backed against the linked Steam Community and Destructoid guides.</span></div><div class="fact-row"><div><span>SUMMON</span><b>Empty Beer Can</b></div><div><span>LOCATION</span><b>Lighthouse</b></div><div><span>ROUTE</span><b>Early boss path</b></div></div><h2>Prepare the summon</h2><p>Keep the Empty Beer Can for the Spider Crab encounter rather than treating it as a normal collection item. Confirm the Lighthouse objective path before using it.</p><a class="button primary" href="/bosses">All boss &amp; special guides →</a></article>`;
  return `<section class="hub"><p class="eyebrow">COMPLETION BOARD</p><h1>All 28 How to Fish<br><i>Game Achievements</i></h1><p class="standfirst">A compact completion overview to use alongside the creature checklist and boss board.</p><ol class="achievement-list">${cards(achievements)}</ol></section>`;
}

const template = await readFile('dist/index.html', 'utf8');
for (const path of routes) {
  const meta = pageMeta[path];
  const canonical = `${domain}${path}`;
  const jsonLd = JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebPage', name: meta.title, description: meta.description, url: canonical, isPartOf: { '@type': 'WebSite', name: 'How to Fish Walkthrough', url: domain } });
  const head = `<meta name="description" content="${escape(meta.description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${escape(meta.title)}"><meta property="og:description" content="${escape(meta.description)}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${jsonLd}</script>`;
  const page = template.replace(/<title>[\s\S]*?<\/title>/, `<title>${escape(meta.title)}</title>`).replace(/<meta name="description"[^>]*>/, '').replace('</head>', `${head}</head>`).replace('<div id="root"></div>', `<div id="root">${layout(contentFor(path))}</div>`);
  const out = path === '/' ? 'dist/index.html' : join('dist', path.slice(1), 'index.html');
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, page);
}
console.log(`prerendered ${routes.length} route HTML files`);
