import type { ReactNode } from "react";

const Crumb = ({ children }: { children: ReactNode }) => (
  <div className="crumb"><a href="/">Home</a><span>›</span><a href="/bosses">Boss Guides</a><span>›</span>{children}</div>
);

const Visual = ({ src, alt, caption, width = 1200, height = 700 }: { src: string; alt: string; caption: string; width?: number; height?: number }) => (
  <figure className="field-capture"><img src={src} alt={alt} width={width} height={height} loading="eager" decoding="async"/><figcaption><span>SITE GUIDE ART</span>{caption}</figcaption></figure>
);

const Facts = ({ summon, location, drop }: { summon: string; location: string; drop: string }) => (
  <div className="fact-row"><div><span>TRIGGER</span><b>{summon}</b></div><div><span>LOCATION</span><b>{location}</b></div><div><span>PROTECT</span><b>{drop}</b></div></div>
);

const Related = ({ links }: { links: [string, string][] }) => (
  <aside className="related"><p className="eyebrow">KEEP READING</p><div>{links.map(([label, href]) => <a href={href} key={href}>{label}<span>→</span></a>)}</div></aside>
);

export function GiantPiranhaGuide() {
  return <article className="article guide-article"><Crumb>Giant Piranha</Crumb><p className="eyebrow">BOSS 02 · FOREST · CHECKED SEP 1, 2026</p><h1>How to Beat Giant Piranha<br/><i>in How to Fish Game</i></h1><p className="standfirst">Giant Piranha is the Forest progression boss. Complete the current Leech objective, exchange the required Leeches for the special bait shown by your live objective, prepare a clear firing lane, and control the small-fish adds before they surround you. After the kill, protect the Giant Piranha Skeleton and finish the Forest hand-in before following the Desert marker.</p>
    <Facts summon="Leech quest bait" location="Forest / Island 2" drop="Giant Piranha Skeleton"/>
    <Visual src="/images/guides/forest/forest-route.svg" alt="Original Forest route diagram for the Giant Piranha quest" caption="The safe route separates the Leech objective, special-bait exchange, boss arena, Skeleton pickup, and final hand-in." width={1200} height={700}/>
    <section><h2>1. Finish the live Leech objective before casting</h2><p>The Forest chain begins with the local quest objective, not an ordinary lure purchase. In the captured route, the player gathers three Leeches and exchanges them for the special bait used for Giant Piranha. Patch wording and the English item label can change, so treat the objective counter and NPC dialogue in your current save as authoritative. Do not cast a regular Beginner Lure and assume a failed spawn means the boss is broken.</p><p>Walk the Forest shoreline and inspect the quest counter after every pickup. Keep the required Leeches separate from food or sale inventory. Return to the quest marker only when the counter is complete, accept the exchange, then verify that a named special item has appeared in inventory. If the counter does not move, reopen the dialogue, confirm you are on the active Forest step, and collect fresh quest Leeches rather than ordinary catches.</p></section>
    <section><h2>2. Prepare the arena, weapon, food, and recovery lane</h2><p>Giant Piranha is dangerous because the boss and its smaller Piranha adds can attack from different angles. Before using the special bait, move away from water, clutter, shop entrances, and any steep edge that can hide the Skeleton after the fight. Choose a lateral lane long enough to strafe while keeping the boss in view. A dependable ranged weapon is safer than trying to stand beside the mouth, but this guide does not claim a mandatory gun, damage number, attachment, or shop price.</p><p>Carry food, load ammunition, leave at least one inventory slot open, and make a clean save. If you are playing co-op, agree who will hold the Skeleton and who will clear adds. The drop is more important than optional meat or Killscore. A clean combat lane also makes a failed attempt easier to diagnose: you can distinguish a real defeat from a body or item that slid into water.</p></section>
    <Visual src="/images/guides/forest/giant-piranha-loop.svg" alt="Original Giant Piranha boss combat-loop diagram" caption="Keep a lateral lane, thin the adds, punish the boss after a committed pass, and reset before the arena closes." width={1200} height={700}/>
    <section><h2>3. Use the movement–adds–boss–reset combat loop</h2><p>Start by watching one complete approach. Giant Piranha pursues aggressively and can become airborne, while smaller Piranhas build pressure around the player. Move sideways instead of retreating blindly. When adds enter the lane, clear the nearest threats before turning back to the boss; letting them accumulate makes healing and reloads unsafe. Defeated adds were observed as a recovery opportunity in the captured route, but no fixed healing value or drop rate is promised.</p><ol className="steps"><li><b>Hold the lateral lane.</b><span>Keep stable ground behind you and the water to one side, not directly at your back.</span></li><li><b>Thin nearby adds.</b><span>Remove the small Piranhas that can interrupt a reload or close your escape route.</span></li><li><b>Punish a committed pass.</b><span>Fire while the boss crosses a predictable line; do not chase it into clutter for one extra hit.</span></li><li><b>Reset and reload.</b><span>Create distance, heal only when the closest add is gone, and repeat the same controlled lane.</span></li></ol><p>The later part of the fight brings stronger airborne and add pressure. That is a cue to shorten damage windows, not to stand still and race the health bar. If the boss leaves view, stop shooting, widen the camera, and find the next approach before spending ammunition.</p></section>
    <Visual src="/images/guides/forest/forest-recovery.svg" alt="Original Forest recovery and Skeleton hand-in diagram" caption="A win is not complete until the Skeleton is found, protected, accepted, and the Desert marker appears." width={1200} height={700}/>
    <section><h2>4. Secure the Skeleton before touching ordinary loot</h2><p>When Giant Piranha falls, stop moving bodies and search the immediate landing area. The progression item is the Giant Piranha Skeleton. Pick it up before meat, food, or optional sale items, then verify it in inventory. Do not cook it, sell it, leave it beside the shoreline, or hand it to an unrelated NPC. Follow the current quest marker back to the Forest hand-in and wait for the next objective or Desert marker to appear.</p><p>If the kill registered but no Skeleton is visible, search beneath the body, around slopes, inside nearby clutter, and along the waterline before reloading. In co-op, check every player inventory. If the item was lost or processed, repeat the Leech exchange and boss attempt from a safer landing lane. Do not sail away on memory alone: the completion test is the accepted hand-in plus the new route marker.</p><div className="checkpoint"><span>FOREST COMPLETE</span><b>Leech objective → special bait → Giant Piranha defeated → Skeleton collected → hand-in accepted → Desert marker confirmed.</b></div></section>
    <Visual src="/images/creatures/encyclopedia-bosses.webp" alt="How to Fish boss encyclopedia capture including Giant Piranha" caption="Use the in-game encyclopedia and live objective to confirm the boss identity; this page avoids unverified health, damage, and value numbers." width={1521} height={876}/>
    <section><h2>Common Giant Piranha failures</h2><div className="troubleshoot"><article><b>No boss appears</b><span>Confirm the Forest quest exchange produced the named special bait; an ordinary lure does not replace it.</span></article><article><b>Adds overwhelm every reload</b><span>Clear the nearest small Piranhas first and shorten each boss damage window.</span></article><article><b>The Skeleton is missing</b><span>Search the landing lane, slopes, water edge, and every co-op inventory before restarting.</span></article><article><b>Desert does not appear</b><span>Return the Skeleton to the active Forest quest NPC and wait for the accepted hand-in or marker update.</span></article></div></section>
    <Related links={[["Forest complete walkthrough","/locations/forest"],["Pufferfish boss guide","/bosses/pufferfish"],["All boss routes","/bosses"]]}/>
  </article>;
}

export function PufferfishGuide() {
  return <article className="article guide-article"><Crumb>Pufferfish</Crumb><p className="eyebrow">BOSS 03 · DESERT · CHECKED SEP 1, 2026</p><h1>How to Beat Pufferfish<br/><i>in How to Fish Game</i></h1><p className="standfirst">Pufferfish is the Desert progression boss and a major difficulty jump. Use Coconut to catch Bing Bong, give that catch to the nearby islander for the Carrot lead, then cast the Carrot only after preparing hard cover, food, ammunition, and a clear landing area. Respect the inflated rolling and airborne poison pressure, secure the Pufferfish Fin, and complete the hand-in that opens Rocks.</p>
    <Facts summon="Carrot" location="Desert / Island 3" drop="Pufferfish Fin"/>
    <Visual src="/images/guides/desert/desert-route.svg" alt="Original Desert route diagram from Coconut to Pufferfish" caption="Follow the current objective through Coconut, Bing Bong, the islander exchange, Carrot, Pufferfish, Fin, and Rocks hand-in." width={1200} height={700}/>
    <section><h2>1. Build the Coconut → Bing Bong → Carrot chain</h2><p>The current practical evidence closes the previously unclear bait step: use Coconut on the third island to catch the creature visibly labeled Bing Bong, then give that catch to the nearby islander to obtain the Carrot lead used for Pufferfish. The recording does not establish a permanent Coconut price, formal NPC name, or whether every patch requires the same body state, so follow the live objective text whenever it differs.</p><p>Keep Bing Bong intact until the islander accepts it. After the exchange, confirm the Carrot is actually in inventory and do not confuse it with ordinary Standard Lure. If the islander does not accept the catch, reopen the dialogue, check that the Desert quest is active, and compare the creature label with the objective. Recatching the correct target is safer than forcing an unverified inventory trick.</p></section>
    <section><h2>2. Set hard cover before you use the Carrot</h2><p>Pufferfish can inflate, roll through the arena, and create airborne poison or gas pressure after its health has been reduced. Open ground invites damage from both the moving body and the surrounding hazard. Pick a tree, shop corner, roof edge, or other solid obstacle that lets you rotate around it without becoming trapped against water. Cover should break the approach, but it is not invulnerability.</p><p>A shotgun recoil jump can reach the top of a Coconut tree, yet the captured test explicitly shows Pufferfish can still attack the player there. Use height only to reposition, never as an AFK safe spot. Load a ranged weapon, carry food, leave inventory space for the Fin, and save before casting. In co-op, decide who keeps the boss moving and who collects the unique drop.</p></section>
    <Visual src="/images/guides/desert/pufferfish-loop.svg" alt="Original Pufferfish roll, gas, cover, and punish loop" caption="Rotate around hard cover, let the roll or airborne hazard pass, fire briefly, then relocate before the next approach." width={1200} height={700}/>
    <section><h2>3. Read inflation and rolling before attacking</h2><p>At the start, watch how the boss turns and how much space the inflated body occupies. When Pufferfish begins a committed roll or broad movement, stop aiming and move across the safe side of cover. Do not back straight away while scoped; that narrows the camera and often sends the player into water, gas, or the boss’s next line. Once the body passes the obstacle, use a short ranged burst and reset.</p><ol className="steps"><li><b>Keep the obstacle between you and the boss.</b><span>Rotate around the solid side instead of standing at the edge of the poison zone.</span></li><li><b>Move when the roll commits.</b><span>Sprint first, then turn the camera after reaching stable ground.</span></li><li><b>Use short damage windows.</b><span>Fire after the pass; do not extend a reload while the boss is already turning back.</span></li><li><b>Relocate as the hazard grows.</b><span>When gas or airborne pressure fills the lane, choose new hard cover rather than forcing the old position.</span></li></ol><p>The guide intentionally avoids a half-health trigger claim. The footage supports inflation and gas after damage has been dealt, but not an exact threshold, radius, damage value, or permanent phase timing. React to what appears on screen rather than waiting for a percentage.</p></section>
    <Visual src="/images/guides/desert/desert-recovery.svg" alt="Original Pufferfish Fin recovery and Rocks unlock diagram" caption="Collect the Fin immediately, complete the Desert hand-in, and confirm the Rocks marker before leaving." width={1200} height={700}/>
    <section><h2>4. Protect the Fin and confirm the Rocks unlock</h2><p>After the boss falls, search the landing area for the Pufferfish Fin before collecting ordinary meat or returning to the boat. Verify the Fin in inventory, then follow the current quest marker to the Desert hand-in. The kill alone does not prove the route is complete. Wait for the Fin to be accepted and confirm the red Rocks marker or onward objective.</p><p>If the Fin is missing, inspect under the body, around the obstacle, along slopes, and near water. Ask every co-op player to check inventory. If it was sold, cooked, or lost, repeat the Bing Bong and Carrot chain and choose a flatter landing area. If Rocks does not appear after the hand-in, reopen the dialogue and check the objective log before sailing blindly.</p><div className="checkpoint"><span>DESERT COMPLETE</span><b>Coconut → Bing Bong → islander → Carrot → Pufferfish defeated → Fin accepted → Rocks marker confirmed.</b></div></section>
    <Visual src="/images/creatures/encyclopedia-bosses.webp" alt="How to Fish boss encyclopedia capture including Pufferfish" caption="The in-game label and live objective remain the authority for identity and progression; numeric combat claims are intentionally omitted." width={1521} height={876}/>
    <section><h2>Common Pufferfish failures</h2><div className="troubleshoot"><article><b>The islander rejects the catch</b><span>Confirm it is Bing Bong caught with Coconut and that the Desert objective is active.</span></article><article><b>The tree still takes damage</b><span>Height is not a safe exploit. Drop to stable ground and rotate around solid cover.</span></article><article><b>The gas closes the lane</b><span>Stop forcing the same obstacle; relocate before aiming or reloading.</span></article><article><b>Rocks remains locked</b><span>The Pufferfish kill is insufficient until the Fin is collected and accepted.</span></article></div></section>
    <Related links={[["Desert complete walkthrough","/locations/desert"],["Albatross boss guide","/bosses/albatross"],["All lures and quest bait","/lures"]]}/>
  </article>;
}

export function AlbatrossGuide() {
  return <article className="article guide-article"><Crumb>Albatross</Crumb><p className="eyebrow">BOSS 04 · ROCKS · CHECKED SEP 1, 2026</p><h1>How to Beat Albatross<br/><i>in How to Fish Game</i></h1><p className="standfirst">Albatross is the aerial story boss on Rocks. Catch Tuna with the Professional Boss Lure, defeat it without selling or processing the body, move the intact Tuna into the island trigger area, and fight from a roof, awning, or doorway instead of trading damage in open ground. Protect the Albatross Head and complete the hand-in for Volcano coordinates.</p>
    <Facts summon="Defeated Tuna body" location="Rocks / Island 4" drop="Albatross Head"/>
    <Visual src="/images/guides/rocks/rocks-two-boss-loop.svg" alt="Original Tuna to Albatross dependency diagram" caption="The encounter is a two-boss chain: Professional Boss Lure, Tuna, intact body, Albatross, Head, then Volcano coordinates." width={1200} height={700}/>
    <section><h2>1. Catch Tuna and preserve the whole body</h2><p>Buy or obtain the Professional Boss Lure shown by the current Rocks route, prepare ammunition and food, and make the Tuna cast from a landing area where the body cannot slide into deep water. Tuna is not disposable sale loot in this sequence. Defeat it, keep the body intact, and verify that you can move it before handling ordinary catches.</p><p>Do not cook the Tuna, sell it, carve it into an unrelated item, or abandon it while shopping. Carry or drag the defeated body through the island structures toward the Albatross trigger shown by the live objective. The captured route confirms the Tuna-to-Albatross dependency but does not measure an exact spawn radius. If the bird does not appear, adjust the body inside the objective area and check the quest state instead of destroying the Tuna.</p></section>
    <Visual src="/images/guides/rocks/rocks-field-layout.svg" alt="Original Rocks field layout showing cover for Albatross" caption="Scout the shop awning, roof, and doorway before moving Tuna into the trigger area." width={1200} height={700}/>
    <section><h2>2. Choose hard cover before the bird arrives</h2><p>Albatross makes aerial passes and drops or throws white projectiles. The full Rocks recording includes an open-ground attempt that ends in death, which makes the lesson unusually clear: do not chase the bird across exposed space. Use the red shop or grill awning, a roof lip, or a doorway that blocks falling projectiles while leaving a narrow firing angle.</p><p>Equip a dependable ranged weapon and enough ammunition for a long aerial fight. A long-range rifle helps when the bird is distant, while a closer ranged option can punish low passes; this page does not prescribe a permanent best weapon, damage number, or upgrade level. Patch 1.0.9 footage also shows weapon switching around a reload, but that is optional, version-sensitive behavior—not a requirement for winning.</p></section>
    <Visual src="/images/guides/rocks/albatross-cover-guide.png" alt="Gameplay reconstruction of safe Albatross cover on Rocks" caption="Expose only enough to take the shot, then let the roof or awning absorb the dangerous part of the aerial pass." width={1280} height={720}/>
    <section><h2>3. Fight the pass, not the whole sky</h2><p>Keep the camera high enough to track the bird, but stand far enough beneath cover that a falling projectile cannot land directly on you. When Albatross begins a pass, stay protected until its path becomes predictable. Step out for one controlled shot or burst, return behind the solid edge, reload under cover, and repeat. If the bird changes direction, give up the shot rather than crossing the entire roofline.</p><ol className="steps"><li><b>Track from cover.</b><span>Use sound and the high camera angle while keeping most of the player behind the roof or doorway.</span></li><li><b>Expose for a short window.</b><span>Fire only when the bird crosses the prepared lane or reaches the safe side of its pass.</span></li><li><b>Break line again.</b><span>Return under cover before reloading; do not stand in the same open spot for the next projectile.</span></li><li><b>Preserve ammunition.</b><span>Skip poor angles and save shots for predictable passes instead of firing at maximum distance.</span></li></ol><p>If you die after Tuna has triggered Albatross, update the game before repeating. Official Patch 1.0.10 notes addressed a progression-breaking state involving death after Tuna and the Albatross spawn. The fix does not make every save recoverable, so keep a clean pre-Tuna save and avoid carrying unrelated unique items.</p></section>
    <section><h2>4. Collect the Head before leaving the arena</h2><p>When Albatross falls, identify the landing point and search for the Albatross Head before touching ordinary meat or returning to the boat. The current clean recording does not show every English inventory label, so use the live item name and objective marker as the final authority. In co-op, verify which player received the drop.</p><p>Carry the Head to the active Rocks NPC and wait for the hand-in to be accepted. The reliable completion test is the appearance of Volcano coordinates or the final route marker, not merely the Albatross health bar reaching zero. If the Head was lost, return to the Professional Boss Lure step, catch another Tuna, preserve its body, and repeat from a safer cover setup.</p><div className="checkpoint"><span>ROCKS COMPLETE</span><b>Professional Boss Lure → Tuna body preserved → Albatross defeated → Head collected → hand-in accepted → Volcano coordinates confirmed.</b></div></section>
    <Visual src="/images/creatures/encyclopedia-bosses.webp" alt="How to Fish boss encyclopedia capture including Tuna and Albatross" caption="Use the game encyclopedia and objective state to verify the two-boss chain without relying on unstable price or damage tables." width={1521} height={876}/>
    <section><h2>Common Albatross failures</h2><div className="troubleshoot"><article><b>Albatross does not spawn</b><span>Keep the defeated Tuna intact and reposition the whole body inside the live objective area.</span></article><article><b>Projectiles hit through the setup</b><span>Move deeper beneath the roof or change to a doorway; visual height alone is not hard cover.</span></article><article><b>You died after the trigger</b><span>Update to the latest patch and recover from a clean pre-Tuna save if progression remains stuck.</span></article><article><b>Volcano stays hidden</b><span>Find and return the Albatross Head; the kill alone does not award the coordinates.</span></article></div></section>
    <Related links={[["Rocks complete walkthrough","/locations/rocks"],["Mutated Bowhead Whale guide","/bosses/mutated-bowhead-whale"],["All five locations","/locations"]]}/>
  </article>;
}

export function MutatedBowheadWhaleGuide() {
  return <article className="article guide-article"><Crumb>Mutated Bowhead Whale</Crumb><p className="eyebrow">FINAL BOSS · VOLCANO · CHECKED SEP 1, 2026</p><h1>How to Beat Mutated Bowhead Whale<br/><i>in How to Fish Game</i></h1><p className="standfirst">This is the normal story route for the final boss, not the bare-hands Handyman challenge. Complete the Scientist’s regular Scientific Lure request, receive the Fish Bucket, catch the ordinary Bowhead Whale, move the whole body to the crater, then use solid black rock lanes to evade the mutated stage. Collect the Whale Fin, return it to the Scientist, and verify the military-boat key before using the RHIB ending route.</p>
    <Facts summon="Whole Bowhead body at crater" location="Volcano / Island 5" drop="Whale Fin"/>
    <Visual src="/images/guides/volcano/01-volcano-arrival.png" alt="Volcano arrival for the Mutated Bowhead Whale route" caption="Finish the Scientist chain and prepare the final-island loadout before beginning either whale encounter." width={1672} height={941}/>
    <section><h2>1. Complete the Scientist request with the regular lure</h2><p>Talk to the yellow-suited Scientist before catching the requested Volcano creatures. Use the regular Scientific Lure, not Scientific Boss Lure. The captured route shows a five-catch request, but source material disagrees about whether any five Scientific catches or five distinct targets count, so the live counter is authoritative. Deliver fresh catches one at a time and verify that the objective advances.</p><p>When the Scientist accepts the completed set, confirm that the Fish Bucket appears in inventory. If the counter does not move, reopen the dialogue and make a new regular Scientific catch. Goblin Shark belongs to the optional Scientific Boss Lure branch and does not replace this story dependency. Do not begin the finale without food, ammunition, a clean save, and inventory space for the Whale Fin.</p></section>
    <Visual src="/images/guides/volcano/02-bowhead-to-crater.png" alt="Regular Bowhead Whale body being moved to the Volcano crater" caption="Use the Fish Bucket for the regular Bowhead, keep the whole body intact, and move it to the crater trigger." width={1672} height={941}/>
    <section><h2>2. Catch the regular Bowhead and protect its whole body</h2><p>Use the Fish Bucket for the regular Bowhead Whale encounter from a landing lane with stable ground. Defeat the whale, but do not sell, cook, carve, or abandon the body. The whole regular Bowhead body is the trigger item for the mutated final stage. Before moving it, reload, heal, and clear the route through Volcano so the body does not become trapped in lava or scenery.</p><p>Carry or drag the Bowhead to the actual crater objective. A piece of meat, an ordinary whale-related item, or a partial drop does not substitute for the body. If Mutated Bowhead Whale does not appear, search for the live crater marker, reposition the intact body inside the trigger area, and verify that the Scientist chain is complete. Preserve a pre-crater save so a physics failure does not force a full island replay.</p></section>
    <Visual src="/images/guides/volcano/03-mutated-bowhead-fight.png" alt="Mutated Bowhead Whale combat at the Volcano crater" caption="Fight from stable black ground: read the lift or charge, cross the safe lane, fire after the pass, and reset before lava closes the route." width={1672} height={941}/>
    <section><h2>3. Use rock geometry and short ranged windows</h2><p>The crater punishes long stationary damage trades. Choose solid black ground beside a large rock or crater edge, with a lateral escape lane that does not cross glowing lava. Keep the camera wide while the whale lines up. When it lifts, charges, or begins a broad body movement, stop aiming and move first. Turn to fire only after the committed motion passes your lane.</p><ol className="steps"><li><b>Hold a stable rock lane.</b><span>Keep hard geometry between you and the whale while preserving enough ground for a sideways escape.</span></li><li><b>Read the commitment.</b><span>When the whale lifts or aligns, stop shooting and watch where the attack will finish.</span></li><li><b>Cross before aiming.</b><span>Sprint to the safe side, avoid glowing lava, and only then turn the camera back.</span></li><li><b>Fire a controlled burst.</b><span>Use the recovery window, reload behind geometry, and repeat instead of chasing across the crater.</span></li></ol><p>The encounter also applies escape pressure, so hiding forever is not a solution. Stay near enough to keep the fight active, but do not trade health for continuous damage. This normal route permits ranged weapons; players attempting Handyman should use the separate bare-hands guide and a dedicated clean save.</p></section>
    <section><h2>4. Recover without converting a win into a stalled save</h2><p>If you fall into lava, stop aiming and prioritize stable ground. If the whale escapes or the white pressure bar empties, reload the clean pre-crater state and shorten the next cycle. If you die, re-establish the safe lane before firing. Do not rush across the arena to recover a few seconds of damage. In co-op, coordinate revives away from the whale’s current path and choose one player to protect the final drop.</p><p>If the Bowhead body disappears before the mutated stage, search the carry route, persistent dropped items, and crater edge. If it was sold, cooked, or irretrievably lost, repeat the Fish Bucket step from a safer landing area. A normal kill does not verify the Handyman achievement; likewise, an achievement attempt does not replace the required Fin hand-in for story completion.</p></section>
    <Visual src="/images/achievements/9f978a5ee40c390d66605ee42333628186ccd337.webp" alt="How to Fish Handyman icon beside the separate final-boss challenge route" caption="The normal guide uses weapons. Open the dedicated Handyman page only when attempting the official bare-hands challenge." width={256} height={256}/>
    <section><h2>5. Pick up the Whale Fin and unlock the ending boat</h2><p>After Mutated Bowhead Whale falls, stop and search the immediate landing area for the Whale Fin. Pick it up before food, meat, or optional loot and verify it in inventory. Return the Fin to the Scientist and wait for the military-boat or RHIB key to be awarded. The final boss defeat is not the last dependency; leaving without the hand-in can make a successful fight look like a broken ending.</p><p>Save after the Scientist accepts the Fin, confirm the key, then use the RHIB or military boat for the mainland ending route. Developer Island and unrelated optional discoveries are not part of this five-location story completion. If the boat remains locked, return to the Scientist, reopen the dialogue, and confirm that the Fin—not ordinary whale meat—was accepted.</p><div className="checkpoint"><span>VOLCANO COMPLETE</span><b>Scientific request → Fish Bucket → Bowhead body → crater → Mutated Bowhead defeated → Whale Fin accepted → military-boat key confirmed.</b></div></section>
    <section><h2>Common final-boss failures</h2><div className="troubleshoot"><article><b>The Scientist counter does not move</b><span>Use the regular Scientific Lure after starting dialogue; the boss lure is a different branch.</span></article><article><b>The mutated stage will not spawn</b><span>Bring the whole regular Bowhead body to the actual crater trigger.</span></article><article><b>Lava ends every attempt</b><span>Stop aiming while retreating, choose black ground first, and fire only after the attack passes.</span></article><article><b>The ending boat is locked</b><span>Collect the Whale Fin, complete the Scientist hand-in, and verify the key before boarding.</span></article></div></section>
    <Related links={[["Volcano complete walkthrough","/locations/volcano"],["Handyman bare-hands guide","/guides/mutated-whale-handyman"],["All boss routes","/bosses"]]}/>
  </article>;
}
