import type { ReactNode } from "react";

const Crumb = ({ section, sectionHref, children }: { section: string; sectionHref: string; children: ReactNode }) => <div className="crumb"><a href="/">Home</a><span>›</span><a href={sectionHref}>{section}</a><span>›</span>{children}</div>;
const Visual = ({ src, alt, caption, width = 1200, height = 700, priority = false }: { src: string; alt: string; caption: string; width?: number; height?: number; priority?: boolean }) => <figure className="field-capture"><img src={src} alt={alt} width={width} height={height} loading={priority ? "eager" : "lazy"} fetchPriority={priority ? "high" : "auto"} decoding="async"/><figcaption><span>SITE GUIDE ART</span>{caption}</figcaption></figure>;
const Related = ({ links }: { links: [string, string][] }) => <aside className="related"><p className="eyebrow">KEEP READING</p><div>{links.map(([label, href]) => <a href={href} key={href}>{label}<span>→</span></a>)}</div></aside>;

export function TunaGuide() {
  return <article className="article guide-article"><Crumb section="Creatures" sectionHref="/creatures">Tuna</Crumb><p className="eyebrow">ROCKS QUEST CATCH · CHECKED SEP 3, 2026</p><h1>How to Catch Tuna<br/><i>in How to Fish Game</i></h1><p className="standfirst">Tuna is not ordinary Rocks sale loot during the story route. Catch it with the Professional Boss Lure, defeat it on stable ground, keep the whole body intact, and move that body into the island objective area to trigger Albatross. This guide focuses on the catch, transport, trigger, and recovery steps that prevent an expensive special-lure attempt from stalling the Volcano route.</p>
    <div className="fact-row"><div><span>LURE</span><b>Professional Boss Lure</b></div><div><span>LOCATION</span><b>Rocks / Island 4</b></div><div><span>QUEST USE</span><b>Whole body triggers Albatross</b></div></div>
    <Visual src="/images/creatures/encyclopedia-professional.webp" alt="How to Fish Professional creature encyclopedia for the Rocks tier" caption="Professional and Professional Boss lures are different items. Verify the full lure name before making the Tuna attempt." width={1521} height={876} priority/>
    <section><h2>1. Reach Rocks with the story chain complete</h2><p>Finish the Desert route before treating Tuna as an active objective. Defeat Pufferfish, collect the Pufferfish Fin, complete the hand-in, and confirm the Rocks marker on Radar. Arriving by exploration or physics does not guarantee that the Tuna-to-Albatross quest state is active. Talk to the Rocks route NPC and read the live objective before buying or equipping a special lure.</p><p>Use the regular Professional Lure for the ordinary Rocks collection. Tuna belongs to the separate Professional Boss Lure branch. Because shop prices and exact labels can change between patches, this guide does not promise a permanent cost. Match the complete item name in your current inventory, bank unrelated quest items, and keep enough money or supplies for a second attempt if the body is lost.</p></section>
    <section><h2>2. Prepare a flat Tuna landing lane</h2><p>Before casting, choose ground where a large defeated body will remain visible and movable. Avoid deep water, narrow docks, steep slopes, shop doors, roof supports, and the edge of the Albatross cover position. The ideal lane has water on one side, a broad strip of solid ground, and a clear path toward the interior objective area.</p><p>Heal, load a dependable ranged weapon, carry food, and make a clean save. Leave inventory and physical space for the body rather than filling the area with ordinary catches. In co-op, agree who will control Tuna and who will keep the carry route clear. Do not let another player sell, cook, carve, or move the body while the objective owner is checking the trigger.</p></section>
    <Visual src="/images/guides/rocks/rocks-field-layout.svg" alt="Original Rocks layout showing the Tuna landing and Albatross cover route" caption="Land Tuna away from water, then move the intact body through a clear Rocks lane before taking cover for Albatross." width={1200} height={700}/>
    <section><h2>3. Catch and subdue Tuna without losing the body</h2><p>Equip the Professional Boss Lure only when the combat lane is ready. Reel the catch toward the prepared shore rather than accepting the first landing angle. Once Tuna reaches land, keep yourself between the body and the sea whenever possible. Use controlled ranged damage and stop moving the catch farther than necessary.</p><ol className="steps"><li><b>Confirm the lure.</b><span>Read Professional Boss Lure in the current UI; the regular Professional Lure does not fill the same role.</span></li><li><b>Pull toward stable ground.</b><span>A longer safe landing is better than a fast catch that drops beside deep water.</span></li><li><b>Subdue from the landward side.</b><span>Keep the Tuna from sliding back toward the ocean while maintaining room to dodge.</span></li><li><b>Stop after the defeat.</b><span>Verify the whole body before interacting with meat, cooking, selling, or another cast.</span></li></ol><p>Tuna has reported sale value in community tables, but selling it now breaks the active story setup. The route value of the whole body is more important than a patch-sensitive price. Complete Albatross and the Volcano hand-in first; collect another Tuna later if you want collection or economy experiments.</p></section>
    <Visual src="/images/guides/rocks/rocks-two-boss-loop.svg" alt="Original Tuna to Albatross two-boss dependency diagram" caption="The body is a bridge item: Professional Boss Lure → Tuna → intact body → Albatross → Head → Volcano coordinates." width={1200} height={700}/>
    <section><h2>4. Move the whole Tuna into the Albatross trigger</h2><p>Carry or drag the defeated Tuna along the interior route indicated by the active objective. The available footage confirms that moving the body through Rocks precedes the Albatross appearance, but it does not establish a permanent radius measured in meters. Use the quest marker and visible spawn response rather than an invented coordinate.</p><p>If Albatross does not appear, confirm the body is still whole, move it farther inside the marked area, reopen the quest dialogue, and check that the correct save owner has progression control. Do not destroy the Tuna while troubleshooting. Once the bird appears, leave the body where it is and move to the roof, awning, or doorway prepared for the aerial fight.</p></section>
    <Visual src="/images/guides/rocks/albatross-cover-guide-1280.webp" alt="Rocks cover reconstruction used after the Tuna triggers Albatross" caption="Tuna finishes its job when Albatross appears. Switch from body transport to hard-cover combat and protect the later Head drop." width={1280} height={720}/>
    <section><h2>5. Recover a failed Tuna setup safely</h2><p>If Tuna falls into water, search the shoreline and reachable shallows before reloading. If another player moved it, check the island structures and ask every player to stop interacting until the body is found. If it was sold, cooked, processed, or irretrievably lost, restore the clean pre-cast save when appropriate or obtain another Professional Boss Lure and repeat the catch.</p><p>If you die after Tuna has spawned Albatross and progression behaves incorrectly, update the game before repeating. Official Patch 1.0.10 addressed a broken state involving death after the Tuna and Albatross sequence. A current version reduces that known risk, but it does not replace a clean save, a safe landing lane, or verification that the Albatross Head is collected after the next fight.</p><div className="checkpoint"><span>TUNA STEP COMPLETE</span><b>Rocks objective active → Professional Boss Lure confirmed → Tuna landed and defeated → whole body preserved → body reaches trigger → Albatross appears.</b></div></section>
    <Related links={[["Albatross boss guide","/bosses/albatross"],["Rocks complete walkthrough","/locations/rocks"],["All 49 creatures","/creatures"]]}/>
  </article>;
}

export function BowheadWhaleGuide() {
  return <article className="article guide-article"><Crumb section="Creatures" sectionHref="/creatures">Bowhead Whale</Crumb><p className="eyebrow">VOLCANO QUEST CATCH · CHECKED SEP 3, 2026</p><h1>How to Catch Bowhead Whale<br/><i>in How to Fish Game</i></h1><p className="standfirst">Bowhead Whale is the first stage of the Volcano finale, not the final boss itself. Complete the Scientist’s regular Scientific Lure request, receive the Fish Bucket, catch and defeat the ordinary Bowhead on safe ground, then transport the whole body to the crater. Only that intact body starts Mutated Bowhead Whale and the final Whale Fin hand-in.</p>
    <div className="fact-row"><div><span>SUMMON</span><b>Fish Bucket</b></div><div><span>LOCATION</span><b>Volcano / Island 5</b></div><div><span>QUEST USE</span><b>Whole body starts final boss</b></div></div>
    <Visual src="/images/creatures/encyclopedia-bosses.webp" alt="How to Fish boss encyclopedia containing Bowhead Whale" caption="Bowhead Whale and Mutated Bowhead Whale are two different route stages. The first must remain a whole transportable body." width={1521} height={876} priority/>
    <section><h2>1. Complete the Scientist’s regular-lure request</h2><p>Reach Volcano through the Albatross Head hand-in and talk to the yellow-suited Scientist before collecting quest catches. Use the regular Scientific Lure. Scientific Boss Lure belongs to the optional Goblin Shark branch and does not replace the Scientist’s request. The captured route shows a five-catch counter, while older descriptions disagree about whether repeats count, so follow the counter in your current save.</p><p>Deliver fresh Scientific catches and check the objective after every hand-in. When the request completes, verify that the Scientist gives you the Fish Bucket. Do not leave the island or begin an optional special-lure fight until the item appears. If the counter stalls, reopen the dialogue and make another regular Scientific catch rather than assuming any five fish from any island will qualify.</p></section>
    <Visual src="/images/guides/volcano/01-volcano-arrival.png" alt="Volcano arrival and safe black-rock lanes for the Bowhead route" caption="Prepare food, ammunition, a clean save, and a body-sized route across stable black ground before using the Fish Bucket." width={1672} height={941}/>
    <section><h2>2. Prepare the shoreline and crater carry route</h2><p>The Fish Bucket starts a large-body encounter, so the landing location matters as much as the weapon. Scout a shoreline with enough solid ground to keep the whale visible after defeat. Then walk the path from that shore to the crater. Remove ordinary catches, avoid narrow lava edges, identify where the body must turn, and choose a recovery save before the special cast.</p><p>Bring food and dependable ranged damage, but do not publish or rely on an old “required” weapon level. Current evidence supports careful positioning and whole-body transport, not a fixed damage table. In co-op, select one player to control the landing and another to watch the carry path. Everyone should understand that the Bowhead body is a quest trigger, not sale or cooking inventory.</p></section>
    <section><h2>3. Catch the regular Bowhead with the Fish Bucket</h2><p>Equip the Fish Bucket and cast only after confirming the active Volcano objective. Pull the whale toward the prepared shore. Keep the fight away from lava, steep drops, the boat, and deep water. When the body reaches land, use controlled damage and preserve the direction needed for transport.</p><ol className="steps"><li><b>Read the item name.</b><span>Use Fish Bucket for Bowhead; do not substitute the regular Scientific or Scientific Boss Lure.</span></li><li><b>Land on the black-rock side.</b><span>Choose stable ground connected to the crater route rather than the closest possible shoreline.</span></li><li><b>Defeat without processing.</b><span>Do not sell, grill, carve, or convert the body after the health bar ends.</span></li><li><b>Confirm the whole model remains.</b><span>Check that the body can be carried or dragged before moving other loot.</span></li></ol><p>If the body begins sliding, move to the landward side and correct the angle before it reaches water or lava. A slower clean catch is more valuable than a fast defeat followed by a lost quest object.</p></section>
    <Visual src="/images/guides/volcano/02-bowhead-to-crater.png" alt="Bowhead Whale body transported toward the Volcano crater" caption="Keep the entire regular Bowhead body intact and move it along the safe lane into the live crater objective." width={1672} height={941}/>
    <section><h2>4. Transport the intact body to the crater</h2><p>Carry or drag the Bowhead along the route you scouted before casting. Use stable black terrain, take wide turns, and stop before every lava lip to correct the body’s angle. Do not sprint blindly while holding the object. If it catches on geometry, release on safe ground, reposition yourself, and pick it up again from a direction that moves it away from the hazard.</p><p>The trigger requires the whole regular Bowhead body. Meat, a partial drop, a similarly named whale item, or merely defeating the first stage does not start the mutated fight. Follow the live crater marker. If nothing happens, confirm the Scientist chain completed, the body is intact, and you reached the actual objective area rather than a visually similar part of Volcano.</p></section>
    <Visual src="/images/guides/volcano/03-mutated-bowhead-fight.png" alt="Mutated Bowhead Whale appearing after the Bowhead crater trigger" caption="When the mutated stage begins, the Bowhead transport step is complete. Change from carry safety to rock-cover combat." width={1672} height={941}/>
    <section><h2>5. Know when the Bowhead step is finished</h2><p>Bowhead is complete when the intact body reaches the crater and Mutated Bowhead Whale activates. From that point, follow the normal final-boss guide: use stable rock geometry, move before aiming when the whale commits, avoid lava, and fire only during controlled windows. Players pursuing Handyman should instead use the dedicated bare-hands route from a clean save.</p><p>If the body disappears before activation, search the shoreline, carry path, crater edge, and persistent dropped objects. Ask every co-op player whether they moved or processed it. If it was sold, cooked, lost in lava, or cannot be recovered, restore the pre-cast save when safe or repeat the Scientist/Fish Bucket step. After the mutated fight, the separate Whale Fin must still be returned to the Scientist for the ending-boat key.</p><div className="checkpoint"><span>BOWHEAD STEP COMPLETE</span><b>Scientific request → Fish Bucket received → regular Bowhead landed → whole body preserved → safe crater transport → Mutated Bowhead Whale activates.</b></div></section>
    <Related links={[["Mutated Bowhead Whale boss guide","/bosses/mutated-bowhead-whale"],["Volcano complete walkthrough","/locations/volcano"],["Handyman bare-hands guide","/guides/mutated-whale-handyman"]]}/>
  </article>;
}

export function LostBossItemsGuide() {
  return <article className="article guide-article"><Crumb section="Guides" sectionHref="/beginner-guide">Lost Boss Items</Crumb><p className="eyebrow">PROGRESSION RECOVERY · CHECKED SEP 3, 2026</p><h1>Lost Boss Item &amp;<br/><i>Boss Not Spawning Guide</i></h1><p className="standfirst">A boss kill is only the middle of most How to Fish story steps. The route advances when the unique body or drop is collected, carried to the correct NPC or arena, accepted, and followed by a new key, coordinate, or Radar marker. Use this recovery guide when a boss will not spawn, a drop disappears, an NPC rejects an item, or the next island remains locked.</p>
    <div className="fact-row"><div><span>FIRST CHECK</span><b>Live objective and inventory</b></div><div><span>PROTECT</span><b>Named bodies and drops</b></div><div><span>COMPLETE WHEN</span><b>Hand-in plus new marker</b></div></div>
    <Visual src="/images/guides/spider-crab-handoff.svg" alt="Original Spider Crab Shell hand-in diagram" caption="The recurring rule starts at Lighthouse: summon, defeat, collect the unique item, hand it in, then verify the next unlock." width={1200} height={700} priority/>
    <section><h2>Start with the route-state checklist</h2><p>Before repeating a fight, read the current objective, reopen the relevant NPC dialogue, and inspect every player inventory. Confirm the exact lure, bait, body, or drop name. Ordinary lure tiers and named story items are not interchangeable. A boss can be defeated correctly while the route remains incomplete because the unique result was left on the ground, entered another player’s inventory, was sold or cooked, or never reached the final hand-in.</p><ol className="steps"><li><b>Check the live objective.</b><span>Make sure the save has reached this island’s active quest rather than arriving early by exploration.</span></li><li><b>Check all inventories.</b><span>In co-op, identify who owns progression and who picked up the unique body or item.</span></li><li><b>Search the landing area.</b><span>Look under the body, on slopes, beside water, around structures, and along the carry path.</span></li><li><b>Reopen the NPC dialogue.</b><span>An accepted hand-in or updated counter is stronger proof than the boss health bar reaching zero.</span></li><li><b>Verify the next marker.</b><span>Do not leave until the key, coordinates, Radar color, or final boat access is visible.</span></li></ol></section>
    <section><h2>Lighthouse: Empty Beer Can, Shell, and Boat Keys</h2><p>Spider Crab requires the Empty Beer Can returned by the Lighthouse beer exchange. A full can or ordinary bait is not the same trigger. If the boss does not appear, repeat the dialogue and confirm the empty item is equipped. After the fight, search for the Spider Crab Shell and give it to the Lighthouse Keeper. The Shell—not ordinary Spider Crab meat—advances progression.</p><p>If the Shell is lost, inspect the shore and every co-op inventory. If it was sold or cannot be recovered, repeat the beer exchange and boss attempt from a flatter landing area. The Lighthouse step is complete only when Boat Keys are awarded; purchase or use the required Radar follow-up and confirm the Forest marker before departing.</p></section>
    <Visual src="/images/guides/forest/forest-recovery.svg" alt="Original Forest recovery diagram for the Giant Piranha Skeleton" caption="Forest recovery centers on preserving the Skeleton, completing the NPC hand-in, and checking the Desert marker." width={1200} height={700}/>
    <section><h2>Forest: Leech bait and Giant Piranha Skeleton</h2><p>If Giant Piranha will not spawn, confirm the live Forest Leech counter and special exchange rather than casting a regular Beginner Lure. Patch wording can change, so use the objective and NPC dialogue as authority. After the fight, collect the Giant Piranha Skeleton before handling meat, food, or add drops.</p><p>If the Skeleton is missing, search beneath the large body, along slopes, around water, and through every co-op inventory. If it was processed or lost, repeat the Leech exchange and create a safer landing lane. Return the Skeleton to the active Forest NPC and wait for the Desert marker; simply defeating Giant Piranha does not finish the route.</p></section>
    <Visual src="/images/guides/desert/desert-recovery.svg" alt="Original Desert recovery diagram for Carrot, Pufferfish Fin, and Rocks" caption="Desert recovery follows Coconut → Bing Bong → islander → Carrot → Pufferfish → Fin → Rocks marker." width={1200} height={700}/>
    <section><h2>Desert: Carrot, Pufferfish Fin, and Rocks marker</h2><p>Build the demonstrated chain by using Coconut to catch Bing Bong and giving that catch to the nearby objective islander for the Carrot lead. If the NPC rejects the catch, verify the creature label and active quest. Cast the Carrot only when the Pufferfish combat lane is ready; Standard Lure is not a substitute.</p><p>After Pufferfish falls, search immediately for the Pufferfish Fin. If it disappears, inspect the ground around cover, the waterline, and co-op inventories. A lost Fin requires another Carrot route and boss attempt unless a clean save can be restored safely. Complete the Fin hand-in and confirm the Rocks marker before leaving Desert.</p></section>
    <Visual src="/images/guides/rocks/rocks-two-boss-loop.svg" alt="Original Rocks recovery chain for Tuna and Albatross Head" caption="Rocks has two protected objects: the intact Tuna body that triggers Albatross and the Head that unlocks Volcano." width={1200} height={700}/>
    <section><h2>Rocks: Tuna body, Albatross Head, and Volcano coordinates</h2><p>If Albatross does not spawn, return to the Tuna step. Use Professional Boss Lure, defeat Tuna on stable ground, and keep the whole body intact. Do not sell, grill, or process it. Move the body into the live objective area; the footage confirms the dependency but not a permanent measured trigger radius.</p><p>After Albatross falls, collect the Albatross Head before ordinary loot. If you died after spawning the bird and progression is broken, update the game; Patch 1.0.10 addressed a known state involving this sequence. If the Head is lost, repeat the Tuna chain from a clean setup. Volcano appears only after the Head is accepted and the final coordinates are confirmed.</p></section>
    <Visual src="/images/guides/volcano/02-bowhead-to-crater.png" alt="Bowhead body transported to the Volcano crater" caption="Volcano uses the entire Bowhead body as a trigger, then a separate Whale Fin for the final Scientist hand-in." width={1672} height={941}/>
    <section><h2>Volcano: Fish Bucket, Bowhead body, Whale Fin, and ending key</h2><p>If the Scientist counter will not advance, start the dialogue and use regular Scientific Lure rather than Scientific Boss Lure. When the current counter completes, confirm the Fish Bucket. Use it for the regular Bowhead Whale, preserve the whole body, and carry that body to the actual crater marker. Meat or a partial whale item will not start the mutated stage.</p><p>If Mutated Bowhead Whale does not spawn, inspect the Bowhead carry route and confirm the Scientist step completed. After the final fight, find the Whale Fin and return it to the Scientist. The final health bar is not the ending unlock: the Fin must be accepted and the military-boat or RHIB key must appear. If the boat remains locked, return to the Scientist before replaying the fight.</p><div className="checkpoint"><span>RECOVERY COMPLETE</span><b>Correct trigger verified → unique body/drop located → correct NPC or arena accepts it → new key, coordinates, marker, or ending access appears.</b></div></section>
    <section><h2>When to reload instead of retrying in place</h2><p>Reload a clean save when a unique body has entered unreachable water or lava, a physics object is irretrievably trapped, a teammate’s inventory state is unclear, or a known patched progression state persists after updating. Do not repeatedly test on the only save while carrying multiple unique items. Record which step was complete before the reload and verify it again afterward.</p><p>When the object is still visible and reachable, recover it in place first. Move ordinary loot away, clear enemies, and use stable ground. The safest prevention is consistent across every island: make a save before the named summon, leave space for the result, assign one co-op carrier, collect the progression item before optional loot, and confirm the next marker before sailing.</p></section>
    <Related links={[["Five-location route","/locations"],["All boss guides","/bosses"],["Beginner save-safety route","/beginner-guide"]]}/>
  </article>;
}

export function MoneyAndCookingGuide() {
  return <article className="article guide-article"><Crumb section="Guides" sectionHref="/beginner-guide">Money &amp; Cooking</Crumb><p className="eyebrow">SAFE ECONOMY ROUTE · CHECKED SEP 3, 2026</p><h1>How to Make Money &amp;<br/><i>Use Cooking Safely</i></h1><p className="standfirst">A reliable How to Fish economy starts with repeatable ordinary catches, visible value inspection, controlled cooking, and strict separation of quest objects. This guide deliberately avoids an unverified “best fish” price table or Casino profit promise. It shows how to stabilize the Lighthouse opening, decide whether to eat, sell, or preserve a catch, use an unlocked grill without destroying progression, and treat Killscore as a bonus rather than required income.</p>
    <div className="fact-row"><div><span>SAFE INCOME</span><b>Ordinary catch and sell</b></div><div><span>COOK ONLY</span><b>Replaceable non-quest catches</b></div><div><span>NEVER PROCESS</span><b>Named progression items</b></div></div>
    <Visual src="/images/guides/beginner/localized/02-survival-loop-cover-en.webp" alt="How to Fish survival and early cash loop guide card" caption="Early money is part of survival: keep enough food and recovery to avoid losing more equipment than a sale earns." width={1280} height={720} priority/>
    <section><h2>1. Stabilize hunger before optimizing profit</h2><p>At Lighthouse, collect nearby Clams and complete the opening instructions before wandering. Buy the first rod through normal progression, make short shore casts, pull catches onto stable ground, subdue them, and inspect the visible value. Keep one replaceable edible catch instead of selling the entire inventory. A player who is starving, unarmed, or forced into a risky recovery trip does not have a profitable loop.</p><p>Use close-shore fishing to reduce travel and retrieval time. The Patch 1.0.10 practical recording also shows releasing an unwanted hooked catch, but the exact input is verified for keyboard and mouse only. Use the current control menu if you play on controller. Release is useful when the catch would waste time or create danger; it is not proof that every lure is preserved or that every future patch behaves identically.</p></section>
    <Visual src="/images/guides/beginner/localized/04-profit-multipliers-cover-en.webp" alt="How to Fish profit and Killscore explainer card" caption="Inspect the displayed result after each catch. Treat multipliers as a measured bonus, not a reason to risk the whole route." width={1280} height={720}/>
    <section><h2>2. Decide: eat, sell, preserve, or discard</h2><p>Use four inventory categories. Eat a replaceable ordinary catch when hunger or health threatens the run. Sell ordinary catches when recovery is stable and the money funds the next required rod, lure, weapon, ammunition, or boat step. Preserve anything named by the active objective, used as special bait, or required for an NPC hand-in. Release an unwanted live catch only when the current controls and lure behavior are understood.</p><ol className="steps"><li><b>Read the live objective.</b><span>Any named catch, body, shell, skeleton, fin, head, bucket, or key mentioned there is protected.</span></li><li><b>Inspect before processing.</b><span>Confirm identity and visible value before choosing food, shop, grill, or storage.</span></li><li><b>Fund the next dependency.</b><span>Buy the item that advances the route before optional upgrades and cosmetic experiments.</span></li><li><b>Keep a recovery reserve.</b><span>Hold enough food and replaceable equipment to survive one failed catch or boss attempt.</span></li></ol><p>This system stays useful even when prices change. It prioritizes route completion and repeatable cash generation over an old ranking of fish values.</p></section>
    <section><h2>3. Protect story items from the economy loop</h2><p>Never sell, eat, grill, carve, or gamble with the Empty Beer Can, Spider Crab Shell, Giant Piranha Skeleton, Carrot, Pufferfish Fin, defeated Tuna body, Albatross Head, Fish Bucket, whole Bowhead body, or Whale Fin while its route step is active. Several of these objects look like catches or body parts that could belong in the normal economy, but their story value is the next island or ending.</p><p>In co-op, appoint one carrier and have that player confirm the item before anyone opens a shop or grill. Make a clean save before named summons. After a boss, collect the unique progression result before ordinary meat. Complete the NPC hand-in and verify the next Radar marker, coordinates, key, or boat access before returning to money farming.</p></section>
    <Visual src="/images/guides/beginner/localized/06-firepower-death-cover-en.webp" alt="How to Fish death and equipment recovery guide card" caption="A failed fight can erase the value of several ordinary sales. Bank irreplaceable items and keep recovery equipment separate." width={1280} height={720}/>
    <section><h2>4. Use cooking only on replaceable catches</h2><p>Cooking is useful after the relevant grill is active and the catch is not part of a quest. The Rocks recording shows an ordinary Red Snapper being processed at a visible 1.50× cooking state in that captured version. Treat that as a versioned example, not a promise that every species, grill, or patch has the same multiplier. Read the current interface before committing a valuable catch.</p><p>Start with a cheap, replaceable ordinary fish. Record the visible value before cooking, process one item, then inspect the result. If the value and behavior are clear, repeat with the same category. Do not infer a universal table from one example. Never test cooking with the Tuna needed for Albatross, the Bowhead body needed for the crater, or a unique boss drop.</p><p>If a grill is unavailable, continue the ordinary catch-and-sell loop instead of forcing progression. Complete the relevant island objective and reopen the NPC dialogue. A safe economy guide should not send players to bypass a story lock or risk unique inventory merely to chase a multiplier.</p></section>
    <Visual src="/images/creatures/encyclopedia-professional.webp" alt="How to Fish Professional creature encyclopedia used to identify replaceable catches" caption="The encyclopedia helps identify the catch tier. The live objective decides whether that specific body is safe to sell or cook." width={1521} height={876}/>
    <section><h2>5. Treat Killscore as optional upside</h2><p>Killscore can improve the result of a catch through combat performance, and the existing achievement route distinguishes ordinary grounded kills from multiplier challenges. However, this material does not justify a permanent multiplier table for every shot, weapon, or patch. Use safe, repeatable finishing actions first. Attempt airborne, long-range, or trick-shot bonuses only with disposable catches and a controlled save.</p><p>A higher multiplier is not profit if it consumes more ammunition, causes a death, loses a weapon, or interrupts a story hand-in. Compare the whole loop: time to catch, ammunition used, food consumed, travel, risk, and final displayed value. When experimenting, change one variable at a time and repeat it before calling the method reliable.</p></section>
    <section><h2>6. Avoid Casino and exploit income claims for now</h2><p>The retained Casino recording does not establish a repeatable current-patch profit route. Random outcomes, inventory state, host behavior, and save behavior are not sufficiently controlled. Do not take story funds, unique drops, or the money required for the next lure into an unverified test. The existing Casino page remains noindex verification notes rather than a public recommendation.</p><p>If you test any community money claim, use a disposable save, record the starting balance, change one variable, repeat at least three clean runs, reload normally, and verify persistence. Until that evidence exists, ordinary fishing, conservative cooking, and route progression are the truthful recommendations.</p><div className="checkpoint"><span>SAFE ECONOMY LOOP</span><b>Stabilize food → catch near shore → inspect identity/value → protect quest items → eat or sell ordinary catches → test cooking only on replaceable inventory.</b></div></section>
    <section><h2>Money and cooking troubleshooting</h2><div className="troubleshoot"><article><b>I sold everything and keep dying</b><span>Keep one edible catch and a recovery reserve before converting the whole inventory to cash.</span></article><article><b>The grill is unavailable</b><span>Return to the current island objective and NPC; do not process a story body at another station.</span></article><article><b>I cooked the Tuna or Bowhead</b><span>Restore a clean save or repeat the required special-catch chain; processed bodies no longer satisfy their trigger role.</span></article><article><b>A multiplier method loses money</b><span>Count ammunition, food, deaths, travel, and replacement gear—not only the final displayed sale value.</span></article></div></section>
    <Related links={[["Beginner first-hour route","/beginner-guide"],["All lure pools and quest bait","/lures"],["Lost boss item recovery","/guides/lost-boss-items"]]}/>
  </article>;
}
