import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { achievements, bosses, creatures, locations, pageMeta, sourceNotes } from './data';
import './styles.css';

const DOMAIN = 'https://howtofishwalkthrough.com';
const nav = [['Beginner Guide','/beginner-guide'],['Creature List','/creatures'],['Boss Guides','/bosses'],['Locations','/locations'],['Lures','/lures']];
function Meta({path}:{path:string}) {
  const known=Boolean(pageMeta[path]);
  const m=pageMeta[path]??{title:'Page Not Found | How to Fish Walkthrough',description:'This How to Fish Walkthrough page does not exist.'};
  useEffect(()=>{
    const url=known?DOMAIN+path:DOMAIN;
    const image=m.image?DOMAIN+m.image:undefined;
    document.title=m.title;
    const set=(name:string,content:string,property=false)=>{let el=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`) as HTMLMetaElement|null;if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',name);document.head.append(el)}el.content=content};
    set('description',m.description);set('og:title',m.title,true);set('og:description',m.description,true);set('og:type','website',true);set('og:url',url,true);set('twitter:card','summary_large_image');set('robots',known?'index,follow':'noindex,follow');if(image){set('og:image',image,true);set('twitter:image',image)}
    let canonical=document.head.querySelector('link[rel="canonical"]') as HTMLLinkElement|null;if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical)}canonical.href=url;
    const guide=path==='/beginner-guide'||path==='/bosses/spider-crab';
    const schema=guide?{'@context':'https://schema.org','@type':'HowTo',name:m.title,description:m.description,url,image,author:{'@type':'Organization',name:'How to Fish Walkthrough'},about:{'@type':'VideoGame',name:'How to Fish',publisher:{'@type':'Organization',name:'Dazed Games'}},dateModified:'2026-08-27'}:{'@context':'https://schema.org','@type':'WebPage',name:m.title,description:m.description,url,isPartOf:{'@type':'WebSite',name:'How to Fish Walkthrough',url:DOMAIN}};
    const id='ld-json';document.getElementById(id)?.remove();const s=document.createElement('script');s.id=id;s.type='application/ld+json';s.text=JSON.stringify(schema);document.head.append(s);return()=>s.remove();
  },[path,m,known]);return null;
}
function Header(){const [open,setOpen]=useState(false);return <header><a className="brand" href="/"><span className="brand-mark">◉</span><span>HOW TO FISH<em> WALKTHROUGH</em></span></a><button className="menu" aria-label="Toggle navigation" aria-expanded={open} aria-controls="primary-navigation" onClick={()=>setOpen(!open)}>☰</button><nav id="primary-navigation" className={open?'open':''}>{nav.map(([label,href])=><a href={href} key={href} onClick={()=>setOpen(false)}>{label}</a>)}</nav></header>}
function Footer(){return <footer><div className="footer-brand">HOW TO FISH <span>WALKTHROUGH</span></div><p>Independent player-made guide for the Dazed Games fishing simulator. Not affiliated with Dazed Games.</p><div className="source-links">Sources: {sourceNotes.map((s,i)=><span key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.label}</a>{i<sourceNotes.length-1?' · ':''}</span>)}</div></footer>}
const Crumb=({children}:{children:React.ReactNode})=><div className="crumb"><a href="/">Chart room</a><span>›</span>{children}</div>;
const Trust=()=> <div className="trust"><b>CHECKED AUG 27, 2026 · PATCH 1.0.9</b><span>Route facts are cross-checked against the official Steam announcement and linked gameplay evidence. Prices, damage values, and timer lengths are intentionally omitted when they may change.</span></div>;
const Related=({links}:{links:[string,string][]})=><aside className="related"><p className="eyebrow">RELATED GUIDES</p><div>{links.map(([label,href])=><a href={href} key={href}>{label}<span>→</span></a>)}</div></aside>;
function GuideVisual({src,alt,caption}:{src:string;alt:string;caption:string}){return <figure className="guide-visual"><img src={src} alt={alt}/><figcaption><span>ORIGINAL FIELD DIAGRAM</span>{caption}</figcaption></figure>}
function Evidence({items}:{items:{label:string;url:string;note:string}[]}){return <aside className="evidence"><p className="eyebrow">WATCH / VERIFY</p><h2>Source notes</h2>{items.map(item=><p key={item.url}><a href={item.url} target="_blank" rel="noreferrer">{item.label} ↗</a><span>{item.note}</span></p>)}<small>Video links are provided for verification. This guide uses original diagrams rather than republishing gameplay frames.</small></aside>}
function Home(){return <><section className="hero"><div className="hero-copy"><p className="eyebrow">THE UNOFFICIAL FIELD GUIDE</p><h1>How to Fish<br/><i>Walkthrough &amp; Guides</i></h1><p className="lede">How to Fish is a 2026 co-op fishing simulator by Dazed Games. Chart every creature, boss, lure, and main location with a route built for new crews.</p><div className="cta"><a className="button primary" href="/beginner-guide">Start at the Lighthouse <b>→</b></a><a className="text-link" href="/creatures">Open creature log</a></div></div><div className="hero-map" aria-hidden="true"><div className="compass">N<span>✦</span></div><div className="wave w1"/><div className="wave w2"/><div className="fish">◁</div><p>CHART 01 / MAIN ROUTE</p></div></section><section className="status-strip"><div><strong>49</strong><span>CREATURES LOGGED</span></div><div><strong>11</strong><span>BOSS &amp; SPECIALS</span></div><div><strong>5</strong><span>MAIN LOCATIONS</span></div><div><strong>28</strong><span>ACHIEVEMENTS</span></div></section><section className="section intro"><p className="eyebrow">PLOT A COURSE</p><h2>Everything has a <i>next step.</i></h2><p>This wiki follows the real game loop: location and story progression on one hand, creature pools and special summons on the other.</p></section><section className="path-grid"> <GuideCard n="01" title="Begin here" copy="A no-nonsense first route from the Lighthouse to your first upgrades." href="/beginner-guide" accent="amber"/><GuideCard n="02" title="Creature log" copy="Search all 49 creatures and keep a personal checklist that stays saved." href="/creatures" accent="mint"/><GuideCard n="03" title="Boss board" copy="Every special creature, its summons, and where it belongs in the route." href="/bosses" accent="coral"/></section><section className="home-split"><div><p className="eyebrow">FIELD NOTES</p><h2>Five main locations.<br/><i>One clear route.</i></h2><p>Lighthouse is the starting location. Forest, Desert, Rocks, and Volcano are the four main islands. Secret Developer Island is a testing area, not part of the normal route.</p><a className="text-link" href="/locations">View location chart →</a></div><div className="location-list">{locations.map((x,i)=><a href="/locations" key={x.name}><span>0{i+1}</span><b>{x.name}</b><small>{x.type}</small><i>→</i></a>)}</div></section><section className="link-matrix" aria-label="All walkthrough sections"><a href="/lures">Lures &amp; Bait <span>→</span></a><a href="/achievements">28 Achievements <span>→</span></a><a href="/bosses/spider-crab">Spider Crab Guide <span>→</span></a></section><section className="tools-banner"><div><p className="eyebrow">YOUR PROGRESS, ON THIS DEVICE</p><h2>Build your own<br/><i>catch checklist.</i></h2></div><a className="button light" href="/creatures">Track all 49 <b>→</b></a></section></>}
function GuideCard({n,title,copy,href,accent}:{n:string;title:string;copy:string;href:string;accent:string}){return <a className={`guide-card ${accent}`} href={href}><span>{n}</span><h3>{title}</h3><p>{copy}</p><b>Open guide →</b></a>}
function Beginner(){return <article className="article guide-article"><Crumb>Beginner Guide</Crumb><p className="eyebrow">FIRST SESSION ROUTE · LIGHTHOUSE → ISLAND 2</p><h1>How to Fish Game<br/><i>Beginner Guide</i></h1><p className="standfirst">This is the first-session route for Dazed Games’ co-op fishing game: complete the tutorial, make your first controlled purchases, set up the Empty Beer Can, clear Spider Crab, and leave Lighthouse with the right quest item. It is a game walkthrough—not real-world fishing advice.</p><Trust/>
<div className="quick-nav" aria-label="On this page"><b>ON THIS PAGE</b><a href="#first-20">First 20 minutes</a><a href="#spider-prep">Spider Crab prep</a><a href="#after-crab">Leave Lighthouse</a><a href="#if-stuck">If you are stuck</a></div>
<GuideVisual src="/images/guides/beginner-lighthouse-loop.svg" alt="Original diagram of the Lighthouse beginner route from tutorial to boat keys" caption="Your first route is a loop, not a grind: learn, fund one useful attempt, prepare the quest item, then hand in the shell."/>
<section id="first-20"><h2>First 20 minutes: make the loop safe</h2><p>The opening tutorial is doing more than teaching buttons. It establishes the economy and the hand-in rhythm you will reuse: catch a creature, bring it somewhere safe, finish it if needed, then sell or hand in the correct item. Finish the sailor’s onboarding tasks before treating Lighthouse as an open-ended collection zone.</p><ol className="steps"><li><b>Complete the tutorial prompts.</b><span>Eat and sell the early catch as directed, then take the first fishing-rod objective. Do not skip NPC dialogue just to farm; the quest sequence tells you which interaction is actually progression-gated.</span></li><li><b>Catch one ordinary creature and pull it inland.</b><span>Once it is hooked, walk it away from the water before you try to finish or carry it. The extra distance gives you a workable window if it tries to run back.</span></li><li><b>Sell enough to fund the next objective, then stop.</b><span>Your immediate goal is a prepared Spider Crab attempt, not a complete creature log. Keep a little food or a usable catch instead of converting every item into money.</span></li><li><b>Talk to the fisherman again before spending freely.</b><span>His beer problem turns into the first boss trigger. This is the checkpoint that distinguishes the Lighthouse story route from normal fishing.</span></li></ol>
<GuideVisual src="/images/guides/beginner-onshore-catch.svg" alt="Original diagram showing a hooked creature pulled inland from the waterline" caption="A simple positioning rule that helps throughout the game: create working space before trying to finish a catch."/>
<div className="checkpoint"><span>CHECKPOINT A</span><b>You are ready to move on when the tutorial is complete and you can reliably catch, move, and sell a basic creature without losing it at the shoreline.</b></div></section>
<section id="spider-prep"><h2>Prepare for Spider Crab before you cast</h2><p>Spider Crab is the first named boss and the route off the starting island. The important part is not rushing into the water with the first item you see. The trigger is an <strong>Empty Beer Can</strong>; the trophy hand-in is the <strong>Spider Crab shell</strong>. Treat both as quest items, not ordinary loot.</p><div className="two-column"><div><h3>Bring / arrange</h3><ul><li>Enough food or a saved catch to recover between attempts.</li><li>A melee option you are comfortable using. A knife or knuckles make solo attempts more forgiving, but avoid publishing a fixed “required” purchase because balance can change.</li><li>Room to move on shore; do not begin with your back to the water.</li><li>The Empty Beer Can equipped as the special lure.</li></ul></div><div><h3>The errand chain</h3><ol><li>Buy a full beer from the Lighthouse shop.</li><li>Give it to the fisherman so he returns the empty can.</li><li>Keep the empty can and equip it on the rod.</li><li>Cast near Lighthouse only when you are ready to fight.</li></ol></div></div><div className="callout"><b>Why wait to cast?</b> The boss fight starts once the crab is hooked. If you die, you may need to repeat the beer errand, so stock a small recovery buffer before you summon it.</div></section>
<section><h2>Fight with a repeatable rhythm</h2><p>Spider Crab’s useful opening comes after its charge: sidestep rather than backpedal, wait for the self-stun, land a few deliberate hits, then move away before it recovers. The goal is to repeat a clean pattern, not to stand in range and trade damage. Terrain can create space, but it is not a permanent exploit—reposition whenever the lane gets cramped.</p><p>Playing co-op changes the pressure, not the objective. Keep one player able to draw the charge while another uses the stun window; stacking on top of each other makes the same lunge punish everyone. In solo, patience and a clear escape lane matter more than squeezing in one extra swing.</p><div className="checkpoint"><span>CHECKPOINT B</span><b>The fight is on track when you can bait a charge, get out of its path sideways, and only re-enter while the crab is visibly stunned.</b></div></section>
<section id="after-crab"><h2>After Spider Crab: the hand-in that unlocks travel</h2><p>Pick up the drops and inspect them before selling anything. The meat is ordinary value or food; the <strong>shell</strong> is the trophy that advances the fisherman’s quest. Hand the shell to the fisherman to receive the boat keys. Then acquire the radar and follow its marker to the next island. Boat keys alone are not the whole navigation step.</p><ol className="steps compact"><li><b>Collect the shell.</b><span>Do not sell or eat it; it is the quest hand-in.</span></li><li><b>Return it to the fisherman.</b><span>Confirm the boat keys are awarded before you clear your inventory.</span></li><li><b>Get the radar.</b><span>Use the marker rather than free-sailing blindly; it is a separate follow-up many players miss.</span></li><li><b>Save at the milestone.</b><span>Patch 1.0.9 retains the game’s manual Save / Main Menu / Quit and one-minute autosave behavior. Use a deliberate save after the boss reward and island unlock.</span></li></ol><a className="button primary" href="/bosses/spider-crab">Open the complete Spider Crab guide <b>→</b></a></section>
<section id="if-stuck"><h2>If the route stalls, check the last completed hand-in</h2><div className="troubleshoot"><article><b>“I cannot summon the crab.”</b><span>Confirm you gave the full beer to the fisherman and received the <strong>Empty Beer Can</strong>. A normal lure will not start this encounter.</span></article><article><b>“The crab keeps killing me.”</b><span>Stop casting immediately after each reset. Rebuild food, make room on shore, then use the charge → sidestep → stun loop. Change difficulty in the menu if needed; Patch 1.0.9 added Easy and Hard settings.</span></article><article><b>“I beat it, but cannot leave.”</b><span>Find the shell, not just meat. Turn the shell in for boat keys, then make sure you have the radar and follow its marker.</span></article><article><b>“My progress looks wrong after a crash.”</b><span>Do not overwrite the save in panic. Check the next load first; the official patch notes say saves occur on Save, Main Menu, Quit, plus a one-minute autosave.</span></article></div></section>
<Evidence items={[{label:'Skoottie — I’m Playing 100% of How to Fish',url:'https://www.youtube.com/watch?v=mK5WaARlT9w',note:'Gameplay reference: opening at 03:03; beer errand 16:25; Spider Crab fight 19:03; shell hand-in 26:44; departure 31:01.'},{label:'Dazed Games — Patch 1.0.9',url:'https://steamcommunity.com/app/4001890/announcements/',note:'Official current-build reference for difficulty options and save behavior, checked Aug 27, 2026.'},{label:'Dazed Games — Official Gameplay Trailer',url:'https://www.youtube.com/watch?v=Hg5pBDKCNFI',note:'Official video reference for the game’s catch, fight, sell, and upgrade loop.'}]}/>
<Related links={[["Spider Crab: summon, combat, hand-in","/bosses/spider-crab"],["All boss & special creatures","/bosses"],["Track all 49 creatures","/creatures"]]}/></article>}
function Creatures(){const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [caught,setCaught]=useState<string[]>(()=>{try{const raw=JSON.parse(localStorage.getItem('htf-caught')||'[]');const names=new Set(creatures.map(c=>c.name));return Array.isArray(raw)?[...new Set(raw.filter((item):item is string=>typeof item==='string'&&names.has(item)))]:[]}catch{return[]}});useEffect(()=>localStorage.setItem('htf-caught',JSON.stringify(caught)),[caught]);const visible=useMemo(()=>creatures.filter(c=>(filter==='All'||c.kind===filter)&&(c.name.toLowerCase().includes(query.toLowerCase()))),[query,filter]);const toggle=(name:string)=>setCaught(x=>x.includes(name)?x.filter(v=>v!==name):[...x,name]);return <section className="hub"><Crumb>Creature List</Crumb><p className="eyebrow">COLLECTION TOOL</p><h1>All 49 How to Fish<br/><i>Game Creatures</i></h1><p className="standfirst">A searchable personal log of 38 regular creatures and 11 boss or special creatures. Checkmarks save only in this browser.</p><div className="progress"><span><b>{caught.length}</b> / 49 logged</span><div><i style={{width:`${caught.length/49*100}%`}}/></div></div><div className="filters"><label><span className="sr-only">Search creatures</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search creature name…"/></label><div>{['All','Creature','Boss / Special'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="creature-grid">{visible.map(c=><label className={`creature ${caught.includes(c.name)?'caught':''}`} key={c.name}><input type="checkbox" checked={caught.includes(c.name)} onChange={()=>toggle(c.name)}/><span className="check">✓</span><span className="number">{String(creatures.indexOf(c)+1).padStart(2,'0')}</span><b>{c.name}</b><small>{c.kind}</small><i>{c.kind==='Boss / Special'?'Special summon':'Regular creature'}</i></label>)}</div></section>}
function Bosses(){return <section className="hub"><Crumb>Boss Guides</Crumb><p className="eyebrow">SPECIAL ENCOUNTERS</p><h1>All How to Fish Game<br/><i>Bosses</i></h1><p className="standfirst">Eleven boss and special creatures sit outside the ordinary collection loop. Bring the specified item, then follow the route cue.</p><div className="boss-grid">{bosses.map((b,i)=><article className="boss" key={b.name}><span>0{i+1}</span><h2>{b.name}</h2><p>{b.note}</p><dl><div><dt>Summon</dt><dd>{b.summon}</dd></div><div><dt>Route</dt><dd>{b.route}</dd></div></dl>{b.name==='Spider Crab'&&<a href="/bosses/spider-crab">Read full guide →</a>}</article>)}</div></section>}
function Locations(){return <section className="hub"><Crumb>Locations</Crumb><p className="eyebrow">MAIN ROUTE CHART</p><h1>How to Fish Game<br/><i>Locations &amp; Islands</i></h1><p className="standfirst">The main route has five locations: Lighthouse plus the four islands Forest, Desert, Rocks, and Volcano. Developer Island is a secret testing area and is not included here.</p><div className="location-cards">{locations.map((l,i)=><article key={l.name}><span>CHART 0{i+1}</span><h2>{l.name}</h2><b>{l.type}</b><p>{l.detail}</p><a href="/bosses">See related encounters →</a></article>)}</div></section>}
function Lures(){const pools=[['Beginner Lure','The opening collection pool and early route progression.'],['Standard Lure','The next regular creature pool after early upgrades.'],['Professional Lure','A later collection pool for advanced progression.'],['Scientific Lure','The final regular lure tier.']];return <section className="hub"><Crumb>Lures &amp; Bait</Crumb><p className="eyebrow">COLLECTION SYSTEM</p><h1>How to Fish Game<br/><i>Lures &amp; Bait</i></h1><p className="standfirst">Lure tiers, not a fixed island-only fish table, shape regular creature collection. Bosses use separate named summons.</p><div className="lure-layout"><div>{pools.map(([title,copy],i)=><article className="lure" key={title}><span>POOL 0{i+1}</span><h2>{title}</h2><p>{copy}</p><a href="/creatures">Browse creature log →</a></article>)}</div><aside><p className="eyebrow">SPECIAL SUMMONS</p><h2>Boss items</h2>{bosses.slice(0,6).map(b=><p key={b.name}><b>{b.summon}</b><span>{b.name}</span></p>)}<a href="/bosses">All 11 summons →</a></aside></div><p className="fineprint">Exact regular-creature pool assignments are being kept conservative until independently verified in current game builds. Special summons listed here are cited below.</p></section>}
function SpiderCrab(){return <article className="article guide-article"><Crumb><><a href="/bosses">Boss Guides</a><span>›</span>Spider Crab</></Crumb><p className="eyebrow">BOSS 01 · LIGHTHOUSE</p><h1>How to Beat Spider Crab<br/><i>in How to Fish Game</i></h1><p className="standfirst">Spider Crab is the first Lighthouse boss. Summon it with the Empty Beer Can, fight the charge rather than the claws, then hand the shell to the fisherman for boat keys. This page separates the trigger, safe combat loop, and post-fight quest step so you do not lose an attempt to the wrong item.</p><Trust/>
<div className="quick-nav" aria-label="On this page"><b>QUICK ROUTE</b><a href="#summon">Summon it</a><a href="#combat">Combat loop</a><a href="#reward">Shell → keys</a><a href="#mistakes">Mistakes</a></div>
<div className="fact-row"><div><span>SUMMON</span><b>Empty Beer Can</b></div><div><span>LOCATION</span><b>Lighthouse shore</b></div><div><span>PROGRESSION</span><b>Shell → boat keys</b></div></div>
<GuideVisual src="/images/guides/spider-crab-combat-loop.svg" alt="Original diagram of the Spider Crab combat loop" caption="The boss is a rhythm check: hold space, sidestep the lunge, hit only during the self-stun, then reset the lane."/>
<section id="summon"><h2>1. Summon Spider Crab correctly</h2><p>You cannot find this boss by fishing with standard bait. First speak with the Lighthouse fisherman and follow his beer errand. Buy a full beer, hand it to him, and retain the <strong>Empty Beer Can</strong> he gives back. Equip that empty can as your lure, then cast around the Lighthouse when you are set up for a real fight.</p><ol className="steps"><li><b>Finish the opening tutorial.</b><span>The early objective gives you the basic catch-and-sell loop and puts you on the Lighthouse quest path.</span></li><li><b>Fund a controlled attempt.</b><span>Keep some food or a backup catch and use a melee weapon you are comfortable with. Solo players generally benefit from a knife or knuckles, but exact costs and upgrade thresholds are patch-sensitive.</span></li><li><b>Trade the beer for the empty can.</b><span>The full can is not the summon. Give it to the fisherman; the returned empty can is the special lure.</span></li><li><b>Equip and cast the empty can near Lighthouse.</b><span>Once the crab is hooked, make space on shore. Do not try to start the fight while trapped between water and obstacles.</span></li></ol><div className="callout"><b>Before you cast:</b> fill your health, clear an escape lane, and decide where you will pull the boss. Resetting the fight may mean repeating the prep chain, so a calm first cast saves time.</div></section>
<section id="combat"><h2>2. Use the charge → stun → punish loop</h2><p>Spider Crab’s main threat is its forward charge. The reliable response is lateral movement: let it commit, sidestep, and wait for the landing/self-stun before you attack. Backpedaling often leaves you in a narrow lane; standing still and trying to out-damage it turns a safe fight into a health trade.</p><div className="combat-grid"><article><span>POSITION</span><b>Stay at a controllable mid-range.</b><p>Leave room to move sideways. Higher ground or nearby objects can buy time, but keep a second route ready in case collision behaves oddly.</p></article><article><span>DODGE</span><b>Strafe the line of the charge.</b><p>Move left or right as the crab commits. Your success condition is a miss, not a counter-hit while it is still moving.</p></article><article><span>PUNISH</span><b>Take only the stun window.</b><p>When stars / the recovery state are visible, land a short melee sequence. As it turns or recovers, leave again instead of chasing.</p></article><article><span>RESET</span><b>Rebuild the lane, then repeat.</b><p>One clean cycle costs less health than forcing damage. In co-op, split the baiting and striking roles rather than clustering together.</p></article></div><p>Watch the second, white bar under a boss health bar as well as health. It represents the encounter’s escape pressure; do not burn your entire run standing in a bad position. If the boss gets a poor angle, reset your movement and prioritize a clean next charge.</p></section>
<section id="reward"><h2>3. The reward is a hand-in, not just a kill</h2><p>When Spider Crab goes down, collect the drops before you sell anything. The <strong>meat</strong> is ordinary food or money; the <strong>Spider Crab shell</strong> is the route item. Return the shell to the fisherman to receive the boat keys. Then purchase and use the radar to identify the next destination. Players who keep only the meat have beaten the fight but have not completed the progression step.</p><GuideVisual src="/images/guides/spider-crab-handoff.svg" alt="Original diagram showing Spider Crab shell becoming boat keys and radar navigation" caption="Separate normal loot from the progression trophy before you touch a vendor. The shell is the item the fisherman needs."/>
<ol className="steps compact"><li><b>Pick up the shell.</b><span>Inspect it and keep it out of the sell / food pile.</span></li><li><b>Give the shell to the fisherman.</b><span>Confirm the boat keys are awarded.</span></li><li><b>Get the radar and follow its marker.</b><span>The radar is a deliberate next step after keys, not a substitute for the quest hand-in.</span></li><li><b>Save after the unlock.</b><span>On the current official patch, manual Save, Main Menu, Quit, and the one-minute autosave are your safety points.</span></li></ol></section>
<section id="mistakes"><h2>Common mistakes and quick recoveries</h2><div className="troubleshoot"><article><b>Using a normal lure</b><span>Only the <strong>Empty Beer Can</strong> starts this boss. Redo the fisherman’s beer exchange if the lure in your rod is wrong.</span></article><article><b>Attacking during the charge</b><span>Stop trading hits. Create side room, dodge the lunge, and make your damage only while the crab is stunned.</span></article><article><b>Selling the shell</b><span>Keep the shell for the fisherman. Meat is the expendable drop; the shell is the island-unlock hand-in.</span></article><article><b>Leaving without navigation</b><span>Boat keys are not the last action. Acquire the radar and use the marker to leave Lighthouse cleanly.</span></article><article><b>Re-attempting while underprepared</b><span>Recover health and clear a lane first. If you are repeatedly dying, use Easy difficulty from the menu; Patch 1.0.9 documents its reduced creature health and damage.</span></article><article><b>Progress loss after a crash</b><span>Load and inspect before making more purchases. The official patch notes say crash-time writes were disabled while regular save points and a one-minute autosave remain.</span></article></div></section>
<Evidence items={[{label:'Skoottie — I’m Playing 100% of How to Fish',url:'https://www.youtube.com/watch?v=mK5WaARlT9w',note:'Gameplay reference: beer errand 16:25; Spider Crab encounter and self-stun 19:03; shell / boat-key hand-in 26:44.'},{label:'Dazed Games — Patch 1.0.9',url:'https://steamcommunity.com/app/4001890/announcements/',note:'Official current-build source for Easy / Normal / Hard settings and save behavior.'},{label:'Dazed Games — Release Date Trailer',url:'https://www.youtube.com/watch?v=YVPYjhBdRbE',note:'Official release-video reference for the game identity and broad co-op loop.'}]}/>
<Related links={[["Beginner route: Lighthouse to Island 2","/beginner-guide"],["All boss & special creatures","/bosses"],["Lighthouse & main locations","/locations"]]}/></article>}
function Achievements(){return <section className="hub"><Crumb>Achievements</Crumb><p className="eyebrow">COMPLETION BOARD</p><h1>All 28 How to Fish<br/><i>Game Achievements</i></h1><p className="standfirst">A compact achievement overview for completion-minded crews. Use it alongside your creature checklist and boss board.</p><ol className="achievement-list">{achievements.map((a,i)=><li key={a}><span>{String(i+1).padStart(2,'0')}</span>{a}</li>)}</ol></section>}
function NotFound(){return <section className="hub empty"><p className="eyebrow">OFF THE CHART</p><h1>This page drifted<br/><i>out of view.</i></h1><a className="button primary" href="/">Return to chart room <b>→</b></a></section>}
function App(){const path=window.location.pathname.replace(/\/$/,'')||'/';const Page=({'/':Home,'/beginner-guide':Beginner,'/creatures':Creatures,'/bosses':Bosses,'/locations':Locations,'/lures':Lures,'/bosses/spider-crab':SpiderCrab,'/achievements':Achievements}[path]||NotFound);return <><Meta path={path}/><Header/><main><Page/></main><Footer/></>};
createRoot(document.getElementById('root')!).render(<App/>);
