import { useEffect, useMemo, useState } from 'react';
import { achievements, bosses, creatures, locations, pageMeta, sourceNotes } from './data';

const DOMAIN = 'https://howtofishwalkthrough.com';
const nav = [['Beginner Guide','/beginner-guide'],['Creature List','/creatures'],['Boss Guides','/bosses'],['Locations','/locations'],['Lures','/lures']];
function Meta({path}:{path:string}) {
  const known=Boolean(pageMeta[path]);
  const m=pageMeta[path]??{title:'Page Not Found | How to Fish Walkthrough',description:'This How to Fish Walkthrough page does not exist.'};
  useEffect(()=>{
    const url=known?DOMAIN+path:DOMAIN;
    const image=m.image?DOMAIN+m.image:undefined;
    document.title=m.title;
    const set=(name:string,content:string,property=false)=>{let el=document.head.querySelector(`meta[${property?'property':'name'}="${name}"]`) as HTMLMetaElement|null;if(!el){el=document.createElement('meta');el.setAttribute(property?'property':'name',name);document.head.append(el)}el.content=content};
    set('description',m.description);set('og:title',m.title,true);set('og:description',m.description,true);set('og:type','website',true);set('og:url',url,true);set('twitter:card','summary_large_image');set('robots',known?'index,follow':'noindex,follow');if(image){set('og:image',image,true);set('twitter:image',image)}
    let canonical=document.head.querySelector('link[rel="canonical"]') as HTMLLinkElement|null;if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical)}canonical.href=url;
    const schema={'@context':'https://schema.org','@graph':[{'@type':'Article',headline:m.title,description:m.description,mainEntityOfPage:url,image,dateModified:'2026-08-27',author:{'@type':'Organization',name:'How to Fish Walkthrough'},about:{'@type':'VideoGame',name:'How to Fish'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'How to Fish Walkthrough',item:DOMAIN},{'@type':'ListItem',position:2,name:path==='/'?'Guides':m.title,item:url}]}]};
    const id='ld-json';document.getElementById(id)?.remove();const s=document.createElement('script');s.id=id;s.type='application/ld+json';s.text=JSON.stringify(schema);document.head.append(s);return()=>s.remove();
  },[path,m,known]);return null;
}
function Header(){const [open,setOpen]=useState(false);return <header><a className="brand" href="/"><span className="brand-mark">◉</span><span>HOW TO FISH<em> WALKTHROUGH</em></span></a><button className="menu" aria-label="Toggle navigation" aria-expanded={open} aria-controls="primary-navigation" onClick={()=>setOpen(!open)}>☰</button><nav id="primary-navigation" className={open?'open':''}>{nav.map(([label,href])=><a href={href} key={href} onClick={()=>setOpen(false)}>{label}</a>)}</nav></header>}
function Footer(){return <footer><div className="footer-brand">HOW TO FISH <span>WALKTHROUGH</span></div><p>Independent player-made guide for the Dazed Games fishing simulator. Not affiliated with Dazed Games.</p><div className="source-links">Sources: {sourceNotes.map((s,i)=><span key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.label}</a>{i<sourceNotes.length-1?' · ':''}</span>)}</div></footer>}
const Crumb=({children}:{children:React.ReactNode})=><div className="crumb"><a href="/">Chart room</a><span>›</span>{children}</div>;
const Trust=()=> <div className="trust"><b>UPDATED AUG 27, 2026 · PATCH 1.0.9</b><span>Direct browser frame review verified the Lighthouse, Empty Beer Can, knife, and post-charge daze visuals in a Douyin 1.0.9 guide. PC Gamer, GamesRadar+, and the official Steam announcement provide the written cross-checks; no platform frames are republished here.</span></div>;
const Related=({links}:{links:[string,string][]})=><aside className="related"><p className="eyebrow">RELATED GUIDES</p><div>{links.map(([label,href])=><a href={href} key={href}>{label}<span>→</span></a>)}</div></aside>;
function GuideVisual({src,alt,caption}:{src:string;alt:string;caption:string}){return <figure className="guide-visual"><img src={src} alt={alt}/><figcaption><span>ORIGINAL FIELD DIAGRAM</span>{caption}</figcaption></figure>}
function Evidence({items}:{items:{label:string;url:string;note:string}[]}){return <aside className="evidence"><p className="eyebrow">SOURCES / VERIFY</p><h2>Claim sources</h2>{items.map(item=><p key={item.url}><a href={item.url} target="_blank" rel="noreferrer">{item.label} ↗</a><span>{item.note}</span></p>)}<small>Evidence boundary: the Douyin and Xiaohongshu clips were directly frame-reviewed in a logged-in browser. No platform frame was downloaded or republished; absence of a watermark is not reuse permission. YouTube remains a public time index only.</small></aside>}
function Home(){return <><section className="hero"><div className="hero-copy"><p className="eyebrow">THE UNOFFICIAL FIELD GUIDE</p><h1>How to Fish<br/><i>Walkthrough &amp; Guides</i></h1><p className="lede">How to Fish is a 2026 co-op fishing simulator by Dazed Games. Chart every creature, boss, lure, and main location with a route built for new crews.</p><div className="cta"><a className="button primary" href="/beginner-guide">Start at the Lighthouse <b>→</b></a><a className="text-link" href="/creatures">Open creature log</a></div></div><div className="hero-map" aria-hidden="true"><div className="compass">N<span>✦</span></div><div className="wave w1"/><div className="wave w2"/><div className="fish">◁</div><p>CHART 01 / MAIN ROUTE</p></div></section><section className="status-strip"><div><strong>49</strong><span>CREATURES LOGGED</span></div><div><strong>11</strong><span>BOSS &amp; SPECIALS</span></div><div><strong>5</strong><span>MAIN LOCATIONS</span></div><div><strong>28</strong><span>ACHIEVEMENTS</span></div></section><section className="section intro"><p className="eyebrow">PLOT A COURSE</p><h2>Everything has a <i>next step.</i></h2><p>This wiki follows the real game loop: location and story progression on one hand, creature pools and special summons on the other.</p></section><section className="path-grid"> <GuideCard n="01" title="Begin here" copy="A no-nonsense first route from the Lighthouse to your first upgrades." href="/beginner-guide" accent="amber"/><GuideCard n="02" title="Creature log" copy="Search all 49 creatures and keep a personal checklist that stays saved." href="/creatures" accent="mint"/><GuideCard n="03" title="Boss board" copy="Every special creature, its summons, and where it belongs in the route." href="/bosses" accent="coral"/></section><section className="home-split"><div><p className="eyebrow">FIELD NOTES</p><h2>Five main locations.<br/><i>One clear route.</i></h2><p>Lighthouse is the starting location. Forest, Desert, Rocks, and Volcano are the four main islands. Secret Developer Island is a testing area, not part of the normal route.</p><a className="text-link" href="/locations">View location chart →</a></div><div className="location-list">{locations.map((x,i)=><a href="/locations" key={x.name}><span>0{i+1}</span><b>{x.name}</b><small>{x.type}</small><i>→</i></a>)}</div></section><section className="link-matrix" aria-label="All walkthrough sections"><a href="/lures">Lures &amp; Bait <span>→</span></a><a href="/achievements">28 Achievements <span>→</span></a><a href="/bosses/spider-crab">Spider Crab Guide <span>→</span></a></section><section className="tools-banner"><div><p className="eyebrow">YOUR PROGRESS, ON THIS DEVICE</p><h2>Build your own<br/><i>catch checklist.</i></h2></div><a className="button light" href="/creatures">Track all 49 <b>→</b></a></section></>}
function GuideCard({n,title,copy,href,accent}:{n:string;title:string;copy:string;href:string;accent:string}){return <a className={`guide-card ${accent}`} href={href}><span>{n}</span><h3>{title}</h3><p>{copy}</p><b>Open guide →</b></a>}
function Beginner(){return <article className="article guide-article"><Crumb>Beginner Guide</Crumb><p className="eyebrow">FIRST SESSION ROUTE · LIGHTHOUSE → ISLAND 2</p><h1>How to Fish Game<br/><i>Beginner Guide</i></h1><p className="standfirst">This is the first-session route for Dazed Games’ co-op fishing game: complete the tutorial, make your first controlled purchases, set up the Empty Beer Can, clear Spider Crab, and leave Lighthouse with the right quest item. It is a game walkthrough—not real-world fishing advice.</p><Trust/>
<div className="quick-nav" aria-label="On this page"><b>ON THIS PAGE</b><a href="#first-20">First 20 minutes</a><a href="#spider-prep">Spider Crab prep</a><a href="#after-crab">Leave Lighthouse</a><a href="#if-stuck">If you are stuck</a></div>
<GuideVisual src="/images/guides/beginner-lighthouse-loop.svg" alt="Original diagram of the Lighthouse beginner route from tutorial to boat keys" caption="Your first route is a loop, not a grind: learn, fund one useful attempt, prepare the quest item, then hand in the shell."/>
<section id="first-20"><h2>First 20 minutes: make the loop safe</h2><p>The opening tutorial establishes the economy and the hand-in rhythm you will reuse. Finish the sailor’s onboarding tasks before treating Lighthouse as an open-ended collection zone. PC Gamer’s route specifically starts with feeding clams, buying the fishing rod, and returning to the sailor before buying the beer for this boss path.</p><ol className="steps"><li><b>Complete the tutorial prompts.</b><span>Follow the sailor’s early objective sequence. It gives the context for the first fishing-rod purchase and ensures the beer exchange is available.</span></li><li><b>Use ordinary catches to fund the next route step.</b><span>PC Gamer recommends feeding the sailor clams or fish for more profitable meals before buying the beer. The purpose is one prepared attempt, not filling the creature log.</span></li><li><b>Keep a recovery option.</b><span>PC Gamer recommends eating seafood before the fight and holding a clam or two for recovery if you are having trouble.</span></li><li><b>Return to the fisherman.</b><span>His beer problem becomes the first boss trigger. This is the checkpoint that distinguishes the Lighthouse story route from normal fishing.</span></li></ol>
<div className="checkpoint"><span>CHECKPOINT A</span><b>You are ready to move on when the tutorial is complete, you have finished the sailor’s early fishing-rod route, and you have enough food or clams for the first boss attempt.</b></div></section>
<section id="spider-prep"><h2>Prepare for Spider Crab before you cast</h2><p>Spider Crab is the first named boss and the route off the starting island. The trigger is an <strong>Empty Beer Can</strong>; the trophy hand-in is the <strong>Spider Crab shell</strong>. PC Gamer and GamesRadar+ both describe the beer-can bait and the shell-to-boat-key result.</p><div className="two-column"><div><h3>Bring / arrange</h3><ul><li>Food or a saved catch for recovery.</li><li>A melee weapon if you are playing solo; PC Gamer recommends a knife or brass knuckles after its author’s fist-only attempts failed.</li><li>The Empty Beer Can equipped as the special lure.</li></ul></div><div><h3>The cited errand chain</h3><ol><li>Buy the full beer after the early tutorial route.</li><li>Give it to the sailor/fisherman.</li><li>Use the Empty Beer Can he returns as bait.</li><li>Reel in Spider Crab and begin the combat loop.</li></ol></div></div><div className="callout"><b>Evidence boundary:</b> the item chain has written support from PC Gamer and GamesRadar+, while the current 1.0.9 visual check is documented in the Douyin source card below.</div></section>
<section><h2>Fight with a repeatable rhythm</h2><p>GamesRadar+ describes Spider Crab’s main attack as a straight charge. Move out of its path, then attack only when stars show the crab is stunned. As it recovers and starts to turn, move away and wait for the next charge. PC Gamer independently describes the post-attack dazed window and recommends patient, short attack attempts.</p><div className="checkpoint"><span>CHECKPOINT B</span><b>The fight is on track when you move away from the charge, attack during the visible dazed / stars window, and leave again as Spider Crab recovers.</b></div></section>
<section id="after-crab"><h2>After Spider Crab: the hand-in that unlocks travel</h2><p>Pick up the drops and inspect them before selling anything. GamesRadar+ identifies the <strong>Spider Crab shell</strong> as the item handed to the Lighthouse keeper for boat keys; it separately notes that the radar tablet is purchased afterward. Keep the shell distinct from ordinary meat until the hand-in is complete.</p><ol className="steps compact"><li><b>Collect the shell.</b><span>Do not sell or eat it; it is the quest hand-in.</span></li><li><b>Return it to the fisherman.</b><span>Confirm the boat keys are awarded before clearing inventory.</span></li><li><b>Buy the radar tablet.</b><span>GamesRadar+ describes it as a separate purchase by the keeper for navigation after the keys.</span></li><li><b>Save at the milestone.</b><span>Official Patch 1.0.6 notes describe manual Save / Main Menu / Quit plus a one-minute autosave.</span></li></ol><a className="button primary" href="/bosses/spider-crab">Open the complete Spider Crab guide <b>→</b></a></section>
<section id="if-stuck"><h2>If the route stalls, check the last completed hand-in</h2><div className="troubleshoot"><article><b>“I cannot summon the crab.”</b><span>Confirm you gave full beer to the fisherman and received the <strong>Empty Beer Can</strong>. PC Gamer and GamesRadar+ both identify it as the boss bait.</span></article><article><b>“The crab keeps killing me.”</b><span>Use the cited charge → dodge → daze → short-attack cycle. Patch 1.0.9 also adds Easy and Hard difficulty settings.</span></article><article><b>“I beat it, but cannot leave.”</b><span>Find the shell, not just meat. GamesRadar+ says it is the boat-key hand-in; then obtain the separate radar tablet.</span></article><article><b>“My progress looks wrong after a crash.”</b><span>Do not overwrite the save in panic. The official patch notes describe manual Save / Main Menu / Quit points plus one-minute autosave.</span></article></div></section>
<Evidence items={[{label:'Douyin @卿 — Spider Crab tutorial',url:'https://www.douyin.com/search/%E6%B8%94%E5%8A%9B%E5%85%A8%E5%BC%80%20%E8%9C%98%E8%9B%9B%E8%9F%B9%20%E6%94%BB%E7%95%A5?modal_id=7677035790840499508&type=general',note:'Direct browser frame review: version 1.0.9; Empty Beer Can by the Lighthouse about 00:12; post-charge daze and knife about 00:35.'},{label:'Xiaohongshu 游戏小挖机 — beginner Spider Crab clip',url:'https://www.xiaohongshu.com/explore/6a8aaf56000000001700b59b',note:'Direct browser frame review, version 1.0.2: charge → visible dizzy state about 00:20; Empty Beer Can visible about 01:05. Older build, used only as a mechanics cross-check.'},{label:'PC Gamer — Spider Crab strategy',url:'https://www.pcgamer.com/games/sim/how-to-fish-spider-crab/',note:'Written route: tutorial, beer → Empty Beer Can bait, food recovery, melee recommendation, dazed attack window, radar, shell-to-boat-key outcome.'},{label:'GamesRadar+ — Spider Crab guide',url:'https://www.gamesradar.com/games/co-op/how-to-fish-spider-crab/',note:'Written cross-check: Empty Beer Can bait, charge / stars-stun timing, shell hand-in, boat keys, separate radar tablet.'},{label:'Dazed Games — Patch 1.0.9',url:'https://steamcommunity.com/app/4001890/announcements/',note:'Official current-build source for difficulty options and save behavior.'}]}/>
<Related links={[["Spider Crab: summon, combat, hand-in","/bosses/spider-crab"],["All boss & special creatures","/bosses"],["Track all 49 creatures","/creatures"]]}/></article>}
function Creatures(){const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [caught,setCaught]=useState<string[]>(()=>{if(typeof window==='undefined')return [];try{const raw=JSON.parse(localStorage.getItem('htf-caught')||'[]');const names=new Set(creatures.map(c=>c.name));return Array.isArray(raw)?[...new Set(raw.filter((item):item is string=>typeof item==='string'&&names.has(item)))]:[]}catch{return[]}});useEffect(()=>localStorage.setItem('htf-caught',JSON.stringify(caught)),[caught]);const visible=useMemo(()=>creatures.filter(c=>(filter==='All'||c.kind===filter)&&(c.name.toLowerCase().includes(query.toLowerCase()))),[query,filter]);const toggle=(name:string)=>setCaught(x=>x.includes(name)?x.filter(v=>v!==name):[...x,name]);return <section className="hub"><Crumb>Creature List</Crumb><p className="eyebrow">COLLECTION TOOL</p><h1>All 49 How to Fish<br/><i>Game Creatures</i></h1><p className="standfirst">A searchable personal log of 38 regular creatures and 11 boss or special creatures. Checkmarks save only in this browser.</p><div className="progress"><span><b>{caught.length}</b> / 49 logged</span><div><i style={{width:`${caught.length/49*100}%`}}/></div></div><div className="filters"><label><span className="sr-only">Search creatures</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search creature name…"/></label><div>{['All','Creature','Boss / Special'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="creature-grid">{visible.map(c=><label className={`creature ${caught.includes(c.name)?'caught':''}`} key={c.name}><input type="checkbox" checked={caught.includes(c.name)} onChange={()=>toggle(c.name)}/><span className="check">✓</span><span className="number">{String(creatures.indexOf(c)+1).padStart(2,'0')}</span><b>{c.name}</b><small>{c.kind}</small><i>{c.kind==='Boss / Special'?'Special summon':'Regular creature'}</i></label>)}</div></section>}
function Bosses(){return <section className="hub"><Crumb>Boss Guides</Crumb><p className="eyebrow">SPECIAL ENCOUNTERS</p><h1>All How to Fish Game<br/><i>Bosses</i></h1><p className="standfirst">Eleven boss and special creatures sit outside the ordinary collection loop. Bring the specified item, then follow the route cue.</p><div className="boss-grid">{bosses.map((b,i)=><article className="boss" key={b.name}><span>0{i+1}</span><h2>{b.name}</h2><p>{b.note}</p><dl><div><dt>Summon</dt><dd>{b.summon}</dd></div><div><dt>Route</dt><dd>{b.route}</dd></div></dl>{b.name==='Spider Crab'&&<a href="/bosses/spider-crab">Read full guide →</a>}</article>)}</div></section>}
function Locations(){return <section className="hub"><Crumb>Locations</Crumb><p className="eyebrow">MAIN ROUTE CHART</p><h1>How to Fish Game<br/><i>Locations &amp; Islands</i></h1><p className="standfirst">The main route has five locations: Lighthouse plus the four islands Forest, Desert, Rocks, and Volcano. Developer Island is a secret testing area and is not included here.</p><div className="location-cards">{locations.map((l,i)=><article key={l.name}><span>CHART 0{i+1}</span><h2>{l.name}</h2><b>{l.type}</b><p>{l.detail}</p><a href="/bosses">See related encounters →</a></article>)}</div></section>}
function Lures(){const pools=[['Beginner Lure','The opening collection pool and early route progression.'],['Standard Lure','The next regular creature pool after early upgrades.'],['Professional Lure','A later collection pool for advanced progression.'],['Scientific Lure','The final regular lure tier.']];return <section className="hub"><Crumb>Lures &amp; Bait</Crumb><p className="eyebrow">COLLECTION SYSTEM</p><h1>How to Fish Game<br/><i>Lures &amp; Bait</i></h1><p className="standfirst">Lure tiers, not a fixed island-only fish table, shape regular creature collection. Bosses use separate named summons.</p><div className="lure-layout"><div>{pools.map(([title,copy],i)=><article className="lure" key={title}><span>POOL 0{i+1}</span><h2>{title}</h2><p>{copy}</p><a href="/creatures">Browse creature log →</a></article>)}</div><aside><p className="eyebrow">SPECIAL SUMMONS</p><h2>Boss items</h2>{bosses.slice(0,6).map(b=><p key={b.name}><b>{b.summon}</b><span>{b.name}</span></p>)}<a href="/bosses">All 11 summons →</a></aside></div><p className="fineprint">Exact regular-creature pool assignments are being kept conservative until independently verified in current game builds. Special summons listed here are cited below.</p></section>}
function SpiderCrab(){return <article className="article guide-article"><Crumb><><a href="/bosses">Boss Guides</a><span>›</span>Spider Crab</></Crumb><p className="eyebrow">BOSS 01 · LIGHTHOUSE</p><h1>How to Beat Spider Crab<br/><i>in How to Fish Game</i></h1><p className="standfirst">Spider Crab is the first Lighthouse boss. Summon it with the Empty Beer Can, fight the charge rather than the claws, then hand the shell to the fisherman for boat keys. This page separates the trigger, safe combat loop, and post-fight quest step so you do not lose an attempt to the wrong item.</p><Trust/>
<div className="quick-nav" aria-label="On this page"><b>QUICK ROUTE</b><a href="#summon">Summon it</a><a href="#combat">Combat loop</a><a href="#reward">Shell → keys</a><a href="#mistakes">Mistakes</a></div>
<div className="fact-row"><div><span>SUMMON</span><b>Empty Beer Can</b></div><div><span>LOCATION</span><b>Lighthouse shore</b></div><div><span>PROGRESSION</span><b>Shell → boat keys</b></div></div>
<GuideVisual src="/images/guides/spider-crab-combat-loop.svg" alt="Original diagram of the Spider Crab combat loop" caption="The boss is a rhythm check: hold space, sidestep the lunge, hit only during the self-stun, then reset the lane."/>
<section id="summon"><h2>1. Summon Spider Crab correctly</h2><p>PC Gamer and GamesRadar+ agree on the gate: complete the opening tutorial route, give the fisherman a full beer, then use the returned <strong>Empty Beer Can</strong> as bait. Standard bait is not the boss trigger.</p><ol className="steps"><li><b>Finish the opening tutorial.</b><span>PC Gamer begins its route with the sailor tutorial and early clam / fishing-rod objectives.</span></li><li><b>Prepare recovery.</b><span>PC Gamer recommends eating seafood before the fight and keeping a clam or two available if needed.</span></li><li><b>Trade beer for the empty can.</b><span>The full can is not the summon. Give it to the fisherman; the returned empty can is the special lure.</span></li><li><b>Equip and cast the empty can.</b><span>GamesRadar+ and PC Gamer both identify it as the bait used to reel in Spider Crab.</span></li></ol><div className="callout"><b>Source boundary:</b> written sources establish the item chain; the Douyin 1.0.9 frame review confirms the visible Empty Beer Can, Lighthouse, knife, and post-charge daze visuals.</div></section>
<section id="combat"><h2>2. Use the charge → stun → punish loop</h2><p>GamesRadar+ describes Spider Crab’s main attack as a straight charge. Move out of that line, then attack once stars show the crab is stunned; leave again as it recovers. PC Gamer independently describes the post-attack dazed window and recommends patient hit-and-run attempts.</p><div className="combat-grid"><article><span>WAIT</span><b>Let the charge commit.</b><p>Keep your focus on avoiding the incoming line rather than attempting a hit before the attack resolves.</p></article><article><span>DODGE</span><b>Move out of the charge.</b><p>GamesRadar+ identifies this move as the boss’s primary attack and advises getting out of the way.</p></article><article><span>PUNISH</span><b>Attack while it is stunned.</b><p>Use the short window marked by stars / the dazed state, as described by GamesRadar+ and PC Gamer.</p></article><article><span>RESET</span><b>Leave as it recovers.</b><p>GamesRadar+ advises running away when it starts turning again, then waiting for the next charge.</p></article></div></section>
<section id="reward"><h2>3. The reward is a hand-in, not just a kill</h2><p>When Spider Crab goes down, keep the <strong>Spider Crab shell</strong> for the fisherman. PC Gamer and GamesRadar+ identify the shell hand-in as the step that awards boat keys. GamesRadar+ separately describes the radar tablet as the follow-up purchase for navigation.</p><GuideVisual src="/images/guides/spider-crab-handoff.svg" alt="Original diagram showing Spider Crab shell becoming boat keys and radar navigation" caption="Keep the shell separate until the fisherman has awarded the boat keys."/>
<ol className="steps compact"><li><b>Pick up the shell.</b><span>Inspect it and keep it out of the sell / food pile.</span></li><li><b>Give the shell to the fisherman.</b><span>Confirm the boat keys are awarded.</span></li><li><b>Get the radar and follow its marker.</b><span>The radar is a deliberate next step after keys, not a substitute for the quest hand-in.</span></li><li><b>Save after the unlock.</b><span>Official Patch 1.0.6 notes describe manual Save, Main Menu, Quit, and one-minute autosave behavior.</span></li></ol></section>
<section id="mistakes"><h2>Common mistakes and quick recoveries</h2><div className="troubleshoot"><article><b>Using a normal lure</b><span>Only the <strong>Empty Beer Can</strong> starts this boss. Redo the fisherman’s beer exchange if the lure in your rod is wrong.</span></article><article><b>Attacking during the charge</b><span>Stop trading hits. Create side room, dodge the lunge, and make your damage only while the crab is stunned.</span></article><article><b>Selling the shell</b><span>Keep the shell for the fisherman. Meat is the expendable drop; the shell is the island-unlock hand-in.</span></article><article><b>Leaving without navigation</b><span>Boat keys are not the last action. Acquire the radar and use the marker to leave Lighthouse cleanly.</span></article><article><b>Re-attempting while underprepared</b><span>Recover health and clear a lane first. If you are repeatedly dying, use Easy difficulty from the menu; Patch 1.0.9 documents its reduced creature health and damage.</span></article><article><b>Progress loss after a crash</b><span>Load and inspect before making more purchases. The official patch notes say crash-time writes were disabled while regular save points and a one-minute autosave remain.</span></article></div></section>
<Evidence items={[{label:'Douyin @卿 — Spider Crab tutorial',url:'https://www.douyin.com/search/%E6%B8%94%E5%8A%9B%E5%85%A8%E5%BC%80%20%E8%9C%98%E8%9B%9B%E8%9F%B9%20%E6%94%BB%E7%95%A5?modal_id=7677035790840499508&type=general',note:'Direct browser frame review: version 1.0.9; Empty Beer Can by the Lighthouse about 00:12; post-charge daze and knife about 00:35.'},{label:'Xiaohongshu 游戏小挖机 — beginner Spider Crab clip',url:'https://www.xiaohongshu.com/explore/6a8aaf56000000001700b59b',note:'Direct browser frame review, version 1.0.2: charge → visible dizzy state about 00:20; Empty Beer Can visible about 01:05. Older build, used only as a mechanics cross-check.'},{label:'PC Gamer — Spider Crab strategy',url:'https://www.pcgamer.com/games/sim/how-to-fish-spider-crab/',note:'Written route: tutorial, Empty Beer Can bait, food recovery, dazed attack window, radar, shell-to-boat-key outcome.'},{label:'GamesRadar+ — Spider Crab guide',url:'https://www.gamesradar.com/games/co-op/how-to-fish-spider-crab/',note:'Written cross-check: Empty Beer Can bait, charge / stars-stun timing, shell hand-in, boat keys, separate radar tablet.'},{label:'Dazed Games — Patch 1.0.9',url:'https://steamcommunity.com/app/4001890/announcements/',note:'Official current-build source for difficulty options and save behavior.'}]}/>
<Related links={[["Beginner route: Lighthouse to Island 2","/beginner-guide"],["All boss & special creatures","/bosses"],["Lighthouse & main locations","/locations"]]}/></article>}
function Achievements(){return <section className="hub"><Crumb>Achievements</Crumb><p className="eyebrow">COMPLETION BOARD</p><h1>All 28 How to Fish<br/><i>Game Achievements</i></h1><p className="standfirst">A compact achievement overview for completion-minded crews. Use it alongside your creature checklist and boss board.</p><ol className="achievement-list">{achievements.map((a,i)=><li key={a}><span>{String(i+1).padStart(2,'0')}</span>{a}</li>)}</ol></section>}
function NotFound(){return <section className="hub empty"><p className="eyebrow">OFF THE CHART</p><h1>This page drifted<br/><i>out of view.</i></h1><a className="button primary" href="/">Return to chart room <b>→</b></a></section>}
export function App({initialPath}:{initialPath?:string}){const path=initialPath??(typeof window==='undefined'?'/':window.location.pathname.replace(/\/$/,'')||'/');const Page=({'/':Home,'/beginner-guide':Beginner,'/creatures':Creatures,'/bosses':Bosses,'/locations':Locations,'/lures':Lures,'/bosses/spider-crab':SpiderCrab,'/achievements':Achievements}[path]||NotFound);return <><Meta path={path}/><Header/><main><Page/></main><Footer/></>};
