type Step = { title: string; body: string };

const Crumb = ({ title, hub = "/bosses", hubLabel = "Video guides" }: { title: string; hub?: string; hubLabel?: string }) => (
  <div className="crumb"><a href="/">Chart room</a><span>›</span><a href={hub}>{hubLabel}</a><span>›</span>{title}</div>
);

const GuideImage = ({ src, alt, caption, width = 1536, height = 1024, eager = false }: { src: string; alt: string; caption: string; width?: number; height?: number; eager?: boolean }) => (
  <figure className="video-guide-image">
    <img src={src} alt={alt} width={width} height={height} loading={eager ? "eager" : "lazy"} decoding="async" fetchPriority={eager ? "high" : "auto"} />
    <figcaption><span>SITE GUIDE ART</span>{caption}</figcaption>
  </figure>
);

const Steps = ({ items }: { items: Step[] }) => (
  <ol className="video-guide-steps">
    {items.map((item, index) => <li key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></li>)}
  </ol>
);

const Related = ({ links }: { links: [string, string][] }) => (
  <aside className="related"><p className="eyebrow">KEEP READING</p><div>{links.map(([label, href]) => <a href={href} key={href}>{label}<span>→</span></a>)}</div></aside>
);

const PracticalTipsDiagram = () => (
  <figure className="guide-visual handyman-diagram">
    <svg viewBox="0 0 1200 650" role="img" aria-labelledby="tips-title tips-desc" xmlns="http://www.w3.org/2000/svg">
      <title id="tips-title">Six practical How to Fish techniques</title>
      <desc id="tips-desc">A six-card field board for shore fishing, weapon cooling, sniper slot switching, boat recovery, shotgun jumping, and charged throwing.</desc>
      <rect width="1200" height="650" rx="36" fill="#0b2527" />
      <text x="60" y="82" fill="#f7e6be" fontFamily="Georgia,serif" fontSize="42" fontWeight="700">PATCH 1.0.10 FIELD TECHNIQUES</text>
      <text x="60" y="120" fill="#a8c7bf" fontFamily="Arial,sans-serif" fontSize="21">Test advanced shortcuts on a clean save before using valuable gear.</text>
      {[
        ["01", "SHORE", "Short cast + release"],
        ["02", "COOL", "Water restores look"],
        ["03", "SWAP", "Double-tap slot"],
        ["04", "PUNCH", "Free a beached boat"],
        ["05", "JUMP", "Shotgun recoil lift"],
        ["06", "CHARGE", "Hold Q, then throw"],
      ].map(([number, label, detail], index) => {
        const column = index % 3;
        const row = Math.floor(index / 3);
        const x = 60 + column * 376;
        const y = 170 + row * 220;
        return <g key={number}><rect x={x} y={y} width="340" height="180" rx="22" fill={row === 0 ? "#163c39" : "#24323d"} stroke="#4d8d7d" strokeWidth="3"/><circle cx={x + 48} cy={y + 50} r="25" fill="#efae58"/><text x={x + 48} y={y + 58} fill="#102824" textAnchor="middle" fontFamily="Arial,sans-serif" fontSize="18" fontWeight="700">{number}</text><text x={x + 88} y={y + 48} fill="#72d4b5" fontFamily="Arial,sans-serif" fontSize="16" fontWeight="700" letterSpacing="2">{label}</text><text x={x + 28} y={y + 112} fill="#f7e6be" fontFamily="Arial,sans-serif" fontSize="24" fontWeight="700">{detail}</text><text x={x + 28} y={y + 146} fill="#a8c7bf" fontFamily="Arial,sans-serif" fontSize="15">Recorded in the supplied 1.0.10 run</text></g>;
      })}
    </svg>
    <figcaption>Original field board: two beginner-safe controls and four version-sensitive movement or equipment techniques.</figcaption>
  </figure>
);

const HandymanLoadoutDiagram = () => (
  <figure className="guide-visual handyman-diagram">
    <svg viewBox="0 0 1200 520" role="img" aria-labelledby="handyman-loadout-title handyman-loadout-desc" xmlns="http://www.w3.org/2000/svg">
      <title id="handyman-loadout-title">Handyman bare-hand preparation checklist</title>
      <desc id="handyman-loadout-desc">A four-part checklist: finish the Volcano chain, store damage tools, keep recovery separate, and begin solo when possible.</desc>
      <rect width="1200" height="520" rx="36" fill="#102824" />
      <text x="64" y="88" fill="#f7e6be" fontFamily="Georgia,serif" fontSize="42" fontWeight="700">HANDYMAN PRE-FIGHT CHECK</text>
      <text x="64" y="126" fill="#a8c7bf" fontFamily="Arial,sans-serif" fontSize="22">Use this before placing the regular Bowhead body at the crater.</text>
      {[
        ['01', ['Finish Volcano', 'story chain'], ['Fish Bucket → Bowhead', '→ crater']],
        ['02', ['Store damage', 'tools'], ['No gun, knife,', 'or explosive']],
        ['03', ['Separate recovery', 'items'], ['Keep food away from', 'weapon slots']],
        ['04', ['Prefer a solo', 'attempt'], ['Co-op final credit', 'may be unclear']],
      ].map(([n, head, body], index) => {
        const x = 64 + index * 282;
        return <g key={String(n)}><rect x={x} y="178" width="248" height="258" rx="24" fill="#1b4139" stroke="#4d8d7d" strokeWidth="3"/><circle cx={x + 44} cy="226" r="25" fill="#efae58"/><text x={x + 44} y="234" fill="#102824" textAnchor="middle" fontFamily="Arial,sans-serif" fontSize="20" fontWeight="700">{n}</text><text x={x + 28} y="286" fill="#f7e6be" fontFamily="Arial,sans-serif" fontSize="21" fontWeight="700">{(head as string[]).map((line, lineIndex) => <tspan x={x + 28} dy={lineIndex === 0 ? 0 : 28} key={line}>{line}</tspan>)}</text><text x={x + 28} y="358" fill="#b9d8cf" fontFamily="Arial,sans-serif" fontSize="17">{(body as string[]).map((line, lineIndex) => <tspan x={x + 28} dy={lineIndex === 0 ? 0 : 24} key={line}>{line}</tspan>)}</text></g>;
      })}
    </svg>
    <figcaption>Original route diagram: verify the bare-hand setup before the mutated stage begins.</figcaption>
  </figure>
);

const HandymanCombatDiagram = () => (
  <figure className="guide-visual handyman-diagram">
    <svg viewBox="0 0 1200 520" role="img" aria-labelledby="handyman-loop-title handyman-loop-desc" xmlns="http://www.w3.org/2000/svg">
      <title id="handyman-loop-title">Mutated Bowhead Whale bare-hand combat loop</title>
      <desc id="handyman-loop-desc">A loop showing safe rock cover, watch for the attack tell, wait for it to pass, use short punches, and reset behind cover.</desc>
      <rect width="1200" height="520" rx="36" fill="#211b26" />
      <text x="64" y="88" fill="#f7e6be" fontFamily="Georgia,serif" fontSize="42" fontWeight="700">CRATER COMBAT LOOP</text>
      <text x="64" y="126" fill="#d2c1d4" fontFamily="Arial,sans-serif" fontSize="22">A short safe window is better than chasing the whale across lava.</text>
      {[
        ['1', ['Hold', 'rock-side cover']],
        ['2', ['Watch the', 'lift / charge']],
        ['3', ['Let the', 'attack pass']],
        ['4', ['Punch briefly,', 'then reset']],
      ].map(([n, label], index) => {
        const x = 88 + index * 280;
        return <g key={String(n)}><circle cx={x} cy="306" r="90" fill="#3e3146" stroke="#e48f63" strokeWidth="5"/><text x={x} y="273" fill="#efae58" textAnchor="middle" fontFamily="Arial,sans-serif" fontSize="30" fontWeight="700">{n}</text><text x={x} y="323" fill="#f7e6be" textAnchor="middle" fontFamily="Arial,sans-serif" fontSize="18" fontWeight="700">{(label as string[]).map((line, lineIndex) => <tspan x={x} dy={lineIndex === 0 ? 0 : 24} key={line}>{line}</tspan>)}</text>{index < 3 && <path d={`M ${x + 108} 306 H ${x + 162}`} stroke="#efae58" strokeWidth="8" markerEnd="url(#arrow)"/>}</g>;
      })}
      <defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#efae58" /></marker></defs>
    </svg>
    <figcaption>Original route diagram: cover, tell, evade, short punches, then cover again.</figcaption>
  </figure>
);

export function CasinoMoneyRouteGuide() {
  return <article className="article guide-article"><Crumb title="Casino money route"/><p className="eyebrow">ARCHIVED TEST NOTE · CURRENT-PATCH VERIFICATION PENDING</p><h1>Casino Money Route<br/><i>Verification Notes</i></h1><p className="standfirst">This page is kept as a save-safety checklist, not as a current money method. The recorded route does not provide enough repeatable evidence to recommend a roulette or inventory loop on the current patch.</p>
    <GuideImage src="/images/guides/reel-of-fortune/reel-machine-hero.png" alt="Stylized How to Fish machine room" caption="The available recording does not establish a repeatable current-patch casino route. Do not treat this cosmetic-machine image as roulette proof." eager/>
    <div className="callout"><b>Do not rely on this for progression:</b> inventory, host, save, and random-result behavior can change. Keep story money and unique boss drops out of any unverified test.</div>
    <Steps items={[
      {title:"Make a clean manual save",body:"Record your balance and bank protected quest items before testing any community claim. A usable test has a known starting state."},
      {title:"Use a small disposable stake",body:"Do not carry your only late-game weapon, rare catch, or the funds required for the next story unlock."},
      {title:"Change one variable at a time",body:"If you test a machine, travel, or reload behavior, change one input and write down the result rather than assuming a single lucky spin is a route."},
      {title:"Reload and recheck",body:"Return to a safe area, reload normally, and confirm that money, weapons, and quest items persisted before repeating anything."},
      {title:"Prefer normal catch-and-sell income",body:"Until three clean current-patch runs reproduce the same result, ordinary sales and story progression are the responsible money plan."},
    ]}/>
    <h2>What would make this page publishable again</h2><p>A future update needs three independently repeatable current-patch runs, a clearly identifiable machine or interaction, beginning and ending balances, normal-save confirmation, and evidence that the result is not ordinary randomness. Until then, this page intentionally avoids a profit promise, exploit instructions, or numerical payout claim.</p>
    <Related links={[["Beginner economy route","/beginner-guide"],["Five-location progression","/locations"],["Reel of Fortune cosmetics","/guides/reel-of-fortune"]]}/>
  </article>;
}

export function MutatedWhaleHandymanGuide() {
  return <article className="article guide-article"><Crumb title="Handyman achievement"/><p className="eyebrow">FINAL BOSS ACHIEVEMENT · CHECKED AUG 31, 2026</p><h1>Mutated Whale<br/><i>Handyman Guide</i></h1><p className="standfirst">Handyman’s official condition is to defeat the final boss with bare hands. This cautious route turns the Mutated Bowhead Whale crater into a controlled punch fight: finish the Volcano chain, remove damage tools, use rock cover, and only step out for short safe windows.</p>
    <GuideImage src="/images/guides/volcano/01-volcano-arrival.png" alt="Volcano arrival area before the final How to Fish boss route" caption="Handyman starts only after the normal Volcano progression has reached the final boss chain." width={1672} height={941} eager/>
    <section id="what-counts"><h2>What Handyman requires — and what this route does not assume</h2><p>The official achievement text says: <strong>“Defeat the final boss with your bare hands.”</strong> The final boss is the mutated stage that begins after the regular Bowhead Whale body reaches the crater. It is not the first whale encounter, a generic Volcano kill, or simply reaching the end area.</p><p>The safest practical interpretation is to use bare hands for the whole mutated fight. That is a conservative route, not a claim that every earlier hit is proven to invalidate the achievement. Because co-op credit and patch behavior can be inconsistent, attempt it solo when possible, bank every damaging tool, and wait for the achievement popup before leaving. If you are helping another player, do not assume their final hit will award your unlock.</p></section>
    <HandymanLoadoutDiagram />
    <section id="unlock-crater"><h2>1. Reach the mutated whale with a clean setup</h2><p>Do the normal Volcano dependency chain first. Catch the required native fish for the Scientist, receive the Fish Bucket, complete the regular Bowhead Whale encounter, and carry the whole body to the crater. The Handyman attempt begins only when Mutated Bowhead Whale is active; do not add an achievement attempt to an unfinished quest run.</p><p>Before placing the body, make a manual save and decide whether this is a dedicated attempt. Store guns, knives, explosives, and any equipment whose damage behavior you cannot rule out. Recovery food is useful for survival, but it should stay clearly separate from weapon slots so an emergency inventory action cannot become an accidental attack. Leave room to collect the Whale Fin after the fight.</p></section>
    <GuideImage src="/images/guides/volcano/02-bowhead-to-crater.png" alt="How to Fish Bowhead Whale body being taken toward the Volcano crater" caption="Carry the regular Bowhead body to the crater to begin the mutated final stage; do not confuse this setup with the Handyman completion itself." width={1672} height={941}/>
    <section id="position"><h2>2. Choose rock geometry before throwing a punch</h2><p>The crater is dangerous because open ground gives the whale a clean line for a charge, body slam, or lava pressure. Start on stable dark ground with a large rock or crater edge between you and the whale. Leave enough lateral space to move around that cover; a narrow lava lip can turn a successful dodge into a fall.</p><p>Do not chase the boss across the arena for damage. Your goal is to make it commit into terrain, turn around, or finish an attack past your lane. Keep the camera wide while moving so you see glowing ground and your escape line. A missed attack that leaves you safe is a better opening than a long combo that strands you in lava.</p></section>
    <GuideImage src="/images/guides/volcano/03-mutated-bowhead-fight.png" alt="Mutated Bowhead Whale fight at the Volcano crater" caption="Stable rock cover creates a repeatable approach: observe the tell, let the movement pass, then take only the nearest punch window." width={1672} height={941}/>
    <HandymanCombatDiagram />
    <section id="fight-loop"><h2>3. Read the tell, punch briefly, reset behind cover</h2><p>Watch the whale rather than staring at your fist reticle. When it lifts, lines up a charge, or begins a broad body movement, stop trying to attack. Move across the safe lane and let the committed attack pass the rock. Only after it lands, turns, or loses its direct line should you step in.</p><ol className="steps"><li><b>Wait for the commitment.</b><span>Hold cover until the approach is obvious. Trading punches before the attack resolves gives up the advantage of the rock.</span></li><li><b>Cross the safe side.</b><span>Use a sideways route with solid ground behind it. Avoid backing straight into glowing lava or an unscouted ledge.</span></li><li><b>Use a short burst of punches.</b><span>Get close enough for a few clear hits, then leave before the boss can reset its path on top of you.</span></li><li><b>Break line of sight again.</b><span>Return to the same rock-side position, heal if necessary, and wait for another committed pass.</span></li></ol><p>The boss also has an escape-pressure bar, so hiding indefinitely can waste the encounter. The balance is deliberate: stay close enough to keep the fight active, but only spend time in the open after a clear miss. Slow, repeated windows beat a panic chase.</p></section>
    <section id="failure-recovery"><h2>4. Recover cleanly when an attempt goes wrong</h2><p>If a weapon fires, an explosive is triggered, a teammate contributes uncertain final damage, or the arena state becomes too chaotic to trust, treat the attempt as compromised. Do not turn a doubtful run into a longer loss. Leave safely if the game allows it, reload the clean pre-crater save, re-check your inventory, and restart as a dedicated bare-hand attempt.</p><p>If the whale defeats you, recover without rushing. Re-establish a rock-side lane, make sure the white escape bar is still manageable, and do not sprint through lava for a single hit. The goal is a reliable achievement unlock, not the fastest final-boss time. In co-op, communicate that this is a solo-credit attempt; if the game’s result is unclear, repeat solo instead of claiming a shared completion.</p></section>
    <section id="completion"><h2>5. Confirm Handyman before moving on</h2><p>Keep using bare hands through the defeat animation, then pause. Wait for the Handyman notification, collect the Whale Fin, and finish the Scientist hand-in as normal. The Whale Fin and military-boat progression confirm the story chain; the achievement popup confirms the separate Handyman condition. If the story finishes but the popup never appears, record that result as unsuccessful and repeat from the clean save rather than guessing which hit counted.</p><div className="checkpoint"><span>HANDYMAN COMPLETE</span><b>Mutated final boss defeated → Handyman notification appears → Whale Fin collected → Scientist hand-in completed.</b></div></section>
    <GuideImage src="/images/achievements/9f978a5ee40c390d66605ee42333628186ccd337.webp" alt="Handyman achievement icon from How to Fish" caption="Use the in-game achievement notification as the only completion confirmation; story progress alone is not proof of Handyman." width={256} height={256}/>
    <Related links={[["Volcano full walkthrough","/locations/volcano"],["All 28 achievements","/achievements"],["All bosses board","/bosses"]]}/>
  </article>;
}

export function TipsAndTricksGuide() {
  return <article className="article guide-article"><Crumb title="Tips and tricks" hub="/beginner-guide" hubLabel="Guides"/><p className="eyebrow">6 PRACTICAL TECHNIQUES · VIDEO-CHECKED SEP 1, 2026</p><h1>How to Fish Game<br/><i>Tips and Tricks</i></h1><p className="standfirst">These six techniques come from an owner-supplied Patch 1.0.10 gameplay recording. Start with the safe fishing and throw controls, then test the equipment and movement shortcuts on a clean save before relying on them during a boss route.</p>
    <div className="trust"><b>PATCH 1.0.10 TEST BOUNDARY</b><span>The recording shows each action working in one PC run. It does not establish controller inputs, exact distance gains, universal item recovery, or future-patch behavior. The route-skip shown in the source is intentionally excluded because bypassing a story key can leave progression state unclear.</span></div>
    <PracticalTipsDiagram/>
    <nav className="quick-nav" aria-label="On this page"><b>ON THIS PAGE</b><a href="#shore-fishing">Fast shore fishing</a><a href="#weapon-cooling">Cool a cooked weapon</a><a href="#sniper-swap">Sniper quick-switch</a><a href="#boat-recovery">Free a boat</a><a href="#shotgun-jump">Shotgun jump</a><a href="#charged-throw">Charged throw</a><a href="#bing-bong">Bing Bong route</a><a href="#tips-faq">FAQ</a></nav>
    <section id="shore-fishing"><h2>1. Fish from the shore without a long cast</h2><p>You do not need a dramatic cast for routine fishing. Stand at a safe edge, put the lure into reachable water, and keep enough dry ground behind you to land the catch. A short placement is easier to control because the fight begins close to the lane you already inspected. The recording shows the player working directly beside the shore rather than trying to reach the middle of the water.</p><ol className="steps compact"><li><b>Choose a clear landing strip.</b><span>Remove loose bodies and avoid a bank that slopes straight back into deep water.</span></li><li><b>Put the lure into nearby water.</b><span>Use the shortest placement that still starts the fishing interaction. Do not step off the edge while watching the float.</span></li><li><b>Land and inspect the catch.</b><span>Pull it onto dry ground, move out of attack range, and decide whether it belongs to the route, collection, food, or sale loop.</span></li><li><b>Right-click to release an unwanted catch.</b><span>The supplied PC run shows a right-click release. Check your current binding if the prompt differs.</span></li></ol><p>The creator reports that this quick release usually preserves the bait in the observed loop, but the clip does not prove a fixed consumption rule. Treat the inventory counter as the test: note the bait count before the cast, release one low-value catch, and check the count again. Do this with ordinary bait before risking a named boss item.</p></section>
    <GuideImage src="/images/guides/beginner/localized/03-bait-hotspots-cover-en.webp" alt="How to Fish bait and shoreline hotspot field card" caption="Use an ordinary shoreline cast to test placement and release controls; keep named story bait for its intended encounter." width={941} height={1672} eager/>
    <section id="weapon-cooling"><h2>2. Cool a cooked weapon in water before replacing it</h2><p>Volcano lava can change a dropped weapon into a visibly cooked state. In the captured run, placing that weapon in water and retrieving it restored the normal appearance. This is a recovery test for a weapon you can safely handle, not a promise that every item, durability state, or future patch will reset the same way.</p><ol className="steps compact"><li><b>Move away from the active fight.</b><span>Do not test beside the final boss, a quest body, or a lava gap that can swallow the item.</span></li><li><b>Make a manual save.</b><span>Use a cheap or replaceable weapon first and keep expensive attachments out of the experiment.</span></li><li><b>Place the affected weapon in shallow water.</b><span>Choose water where the item remains visible and reachable from land.</span></li><li><b>Retrieve and inspect it.</b><span>Compare its appearance and normal use state before returning to the route.</span></li></ol><p>If the weapon sinks, disappears, remains altered, or cannot be picked up, stop. Reload the safe state rather than repeating the same drop with better gear. The recording proves one visible recovery sequence only; it does not prove that water repairs lost statistics or reverses every environmental effect.</p></section>
    <GuideImage src="/images/guides/volcano/01-volcano-arrival.png" alt="Volcano arrival with black rock lanes and lava hazards" caption="Use shallow, controlled water away from the boss route if you test recovery on a visibly cooked weapon." width={1672} height={941}/>
    <section id="sniper-swap"><h2>3. Double-tap the sniper slot for a faster follow-up</h2><p>After a sniper shot, the supplied run double-taps the weapon’s numbered inventory slot. The visible bolt-cycle is skipped and the weapon is ready sooner for the next shot. This is an animation cancel observed on Patch 1.0.10, so it belongs in the advanced category: useful when it works, easy to lose after an update, and never required for a safe boss strategy.</p><ol className="steps compact"><li><b>Fire one controlled shot.</b><span>Use a stationary ordinary target or an empty practice lane so a missed input does not cost a boss attempt.</span></li><li><b>Tap the sniper’s number twice.</b><span>The first input changes or reselects the slot; the second returns the weapon to hand.</span></li><li><b>Wait for a clear ready state.</b><span>Do not fire solely because the animation looks shorter. Confirm the weapon responds normally.</span></li><li><b>Compare with the standard cycle.</b><span>If the timing is inconsistent, use the intended bolt animation and reload rhythm.</span></li></ol><p>Do not build a loadout around an exact fire-rate gain: the video contains no frame-timed measurement. In co-op, avoid testing this while another player crosses your line. A faster follow-up is only valuable when the lane, ammunition count, and target read remain under control.</p></section>
    <GuideImage src="/images/guides/beginner/localized/06-firepower-death-cover-en.webp" alt="How to Fish late-game firearm and recovery field card" caption="Practice numbered-slot switching with replaceable ammunition before bringing the shortcut to Rocks or Volcano." width={941} height={1672}/>
    <section id="boat-recovery"><h2>4. Punch a beached boat back toward open water</h2><p>A boat can wedge against the shore or scenery before the route is complete. The recording shows the player punching the hull to move and steer it back toward open water. Use this as a recovery technique for a boat you already unlocked. The same source demonstrates pushing a boat toward another island without the expected key, but that skip is not part of this guide because the destination may load while the quest, hand-in, or key state remains incomplete.</p><ol className="steps compact"><li><b>Stop the engine and inspect the hull.</b><span>Find the side touching land and the nearest direction with continuous open water.</span></li><li><b>Stand on stable ground.</b><span>Do not position yourself between the hull and deep water or a cliff edge.</span></li><li><b>Punch the landward side in short bursts.</b><span>Watch whether the bow rotates or the whole hull slides; adjust your angle after each movement.</span></li><li><b>Board only when the boat floats freely.</b><span>Restart normal steering and confirm the active route marker before departing.</span></li></ol><p>If the boat moves deeper into terrain, stop and reload rather than adding more physics force. Never use a progression drop, explosive, or expensive weapon as a pushing tool. The goal is to recover a legitimate vehicle state, not to bypass the NPC chain that awards access.</p></section>
    <section id="shotgun-jump"><h2>5. Use shotgun recoil for extra height</h2><p>The recorded player combines a jump with a downward shotgun blast to reach a coconut tree. The recoil produces a visible lift beyond the normal jump. It is a situational movement tool, not a damage-free shortcut: the same sequence shows Pufferfish still able to hit the player, and the clip does not measure fall damage, ammunition cost efficiency, or a maximum reachable height.</p><ol className="steps compact"><li><b>Choose open ground and a low test ledge.</b><span>Remove hostile creatures and keep water, lava, roofs, and steep drops out of the landing zone.</span></li><li><b>Face the intended landing direction.</b><span>Build a straight approach so the camera does not need a large correction in the air.</span></li><li><b>Jump, aim down, and fire once.</b><span>Use one blast to read the recoil. Do not spam shots while you are unable to see the landing.</span></li><li><b>Recover before repeating.</b><span>Check health, ammunition, and nearby enemies; climb normally when a safe path exists.</span></li></ol><p>For the Desert coconut objective, the normal terrain route should remain your first choice. Use the recoil jump only after the story objective is active and the Coconut can be recovered safely. A movement trick that reaches the tree but leaves you without health or ammunition for Pufferfish is a poor trade.</p></section>
    <section id="charged-throw"><h2>6. Hold Q to charge a longer throw</h2><p>A quick tap and a charged throw are different actions. In the supplied PC recording, holding Q displays a circular charge indicator and increases the throw distance before release. This is the most broadly useful advanced control because it helps move ordinary bodies, test value tricks, and clear clutter from a work area. It can also lose an item permanently if the landing zone is water, lava, or a steep slope.</p><ol className="steps compact"><li><b>Pick up a cheap practice object.</b><span>Do not learn with a boss trophy, special bait, expensive weapon, or the whole Bowhead body.</span></li><li><b>Point at open, level ground.</b><span>Leave more space than a normal drop needs and keep other players clear.</span></li><li><b>Hold Q and watch the circle.</b><span>Build charge while keeping the projected direction stable; the recording does not establish a universal maximum duration.</span></li><li><b>Release and mark the landing.</b><span>Compare one short hold with one longer hold, then retrieve the object before continuing.</span></li></ol><p>Controller bindings are not established by this PC clip. If Q does nothing, inspect the current control menu rather than assuming the mechanic was removed. When moving a progression item, prefer carrying or a short controlled placement. Distance is useful only when the object remains visible and recoverable.</p></section>
    <section id="bing-bong"><h2>Desert application: Coconut → Bing Bong → Carrot</h2><p>The same Patch 1.0.10 recording supplies a missing Desert dependency. Use the Coconut from the palm area as bait to catch the creature visibly labeled <strong>Bing Bong</strong>. Bring that catch to the nearby islander involved in the objective, wait for the exchange to register, and inspect the reward. The demonstrated chain leads to the <strong>Carrot</strong> used for Pufferfish.</p><p>The footage does not expose a reliable official English name for the islander or a readable Coconut price, so this guide identifies the NPC by location and function. The full <a href="/locations/desert#tourist">Desert walkthrough</a> contains the save, hand-in, Pufferfish, Fin, and Rocks checks. Do not cook, sell, or throw Bing Bong after the objective catch, and do not cast the Carrot until the fight lane is ready.</p></section>
    <section id="tips-faq"><h2>Tips and tricks FAQ</h2><div className="troubleshoot"><article><b>Do these techniques work on controller?</b><span>The source verifies PC inputs only. Use the current control menu to find the equivalent release, slot, and throw bindings.</span></article><article><b>Will the sniper cancel always work?</b><span>No guarantee is made. It is a Patch 1.0.10 animation shortcut; use the normal bolt cycle if a later build changes it.</span></article><article><b>Can I reach the next island without its key?</b><span>The source shows a physics route, but this guide excludes it. Complete the boss drop, NPC hand-in, key, and marker chain to protect progression state.</span></article><article><b>Can water repair every lava-damaged item?</b><span>Only one weapon’s visible cooked state was reversed in the run. Test a cheap item on a clean save and do not infer a universal repair system.</span></article><article><b>Which tips belong in the first hour?</b><span>Use short shore fishing, right-click release, and charged throwing with cheap objects. Save weapon cancels, recoil jumps, and environmental recovery for controlled tests.</span></article></div></section>
    <Related links={[["Beginner route","/beginner-guide#practical-tips"],["Desert Bing Bong route","/locations/desert#tourist"],["All lures and quest bait","/lures"],["Five-location progression","/locations"]]}/>
  </article>;
}
